name: orsed
recipe: drupal9

config:
  php: 7.4
  webroot: web
  xdebug: true
  database: mysql
services:
  appserver:
    build:
      - composer install
    overrides:
      volumes:
        - type: bind
          # Linux user: add 'export LANDO_SSH_AUTH_SOCK="${SSH_AUTH_SOCK}"' at the end of your ~/.bashrc:
          # Mac user: MacOS specific path is here as the variable default value, nothing to do.
          source: "${LANDO_SSH_AUTH_SOCK:-/run/host-services/ssh-auth.sock}"
          target: /run/host-services/ssh-auth.sock
      environment:
        DRUSH_OPTIONS_URI: "https://orsed.lndo.site"
        SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
  node:
    type: node
    build:
      - npm install
tooling:
  node:
    service: appserver
  npm:
    service: appserver
