name: orse_d
recipe: drupal9

config:
  php: 7.4
  webroot: web
  xdebug: true

services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
    build:
      - composer install
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://orsed.lndo.site"
tooling:
  node:
    service: appserver
  npm:
    service: appserver
