<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZjmuego\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZjmuego/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZjmuego.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZjmuego\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZjmuego\appProdProjectContainer([
    'container.build_hash' => 'Zjmuego',
    'container.build_id' => 'dd70a43f',
    'container.build_time' => 1613747182,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZjmuego');
