<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVjthn9w\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVjthn9w/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVjthn9w.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVjthn9w\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVjthn9w\appProdProjectContainer([
    'container.build_hash' => 'Vjthn9w',
    'container.build_id' => '22ab002d',
    'container.build_time' => 1619542830,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVjthn9w');
