<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => '45.132.241.179',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'orse_mautic',
	'db_user' => 'orse_mautic',
	'db_password' => 'skzNr{$$HJ*_5>8-',
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'mailer_from_name' => 'Igor Agatti',
	'mailer_from_email' => 'igor@igoragatti.com',
	'mailer_transport' => 'smtp',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_amazon_region' => 'us-east-1',
	'mailer_amazon_other_region' => null,
	'mailer_api_key' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/../var/spool',
	'secret_key' => '490edc6fbc60279deab9cf3836dd3037939a17e254bf0251304d5735a070f134',
	'site_url' => 'http://orseeventos.com.br/mkt',
);
