---
php_version: '8.1'
php_packages:
  - "php{{ php_version }}"
  - "php{{ php_version }}-cli"
  - "php{{ php_version }}-fpm"
  - "php{{ php_version }}-mysql"
  - "php{{ php_version }}-gd"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-mbstring"
  - "php{{ php_version }}-xml"
  - "php{{ php_version }}-zip"
  - "php{{ php_version }}-intl"
  - "php{{ php_version }}-opcache"
  - "php{{ php_version }}-bcmath"
  - unzip
  - git
php_fpm_service: "php{{ php_version }}-fpm"
php_ini_cli_path: "/etc/php/{{ php_version }}/cli/php.ini"
php_ini_fpm_path: "/etc/php/{{ php_version }}/fpm/php.ini"
php_memory_limit: '256M'
php_upload_limit: '64M'
php_post_max_size: '64M'
php_max_execution_time: '120'
php_timezone: 'America/Sao_Paulo'
