all:
  hosts:
    drupal_prod:
      ansible_host: 164.152.196.4
      ansible_user: ubuntu
      ansible_port: 22
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      deployment_root: /var/www/orse/orse_d
      drupal_console: ./vendor/bin/drush
      nginx_server_name: 164.152.196.4
      php_version: '8.1'
      drupal_db_name: orse
      drupal_db_user: orse
      drupal_db_password: Jj^^CL1Q@maG
  vars:
    drupal_deploy_user: deploy
    drupal_deploy_group: www-data
