<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Functions to support theming in the orse theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function orse_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function orse_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function orse_preprocess_node(&$variables) {

}

/**
 * Implements hook_HOOK_form_alter () for node.html.twig.
 */
function orse_form_user_form_alter(&$form, FormStateInterface $form_state) {
  $form["select_roles"]["#title"] = t("Are you a photographer or client?");
}
