---
- name: Provision Drupal server
  hosts: drupal_prod
  become: true
  vars:
    deployment_root: "{{ hostvars[inventory_hostname].deployment_root | default('/var/www/orse/orse_d') }}"
    php_version: "{{ hostvars[inventory_hostname].php_version | default('8.1') }}"
  roles:
    - role: php
      tags: [php]
    - role: composer_drush
      tags: [composer, drush]
    - role: mariadb
      tags: [mariadb, database]
    - role: nginx
      tags: [nginx, webserver]
    - role: firewall
      tags: [firewall]
    - role: drupal_system
      tags: [drupal]
