<?php
global $base_url;
global $product_entity;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\UrlHelper;
function apar_theme_suggestions_page_alter(array &$suggestions, array $variables) {
	if ($node = \Drupal::routeMatch()->getParameter('node')) {
		$suggestions[] = 'page__node__' . $node->getType();
	}
}
function apar_preprocess_block(&$variables) {
	global $base_url;
	switch ($variables['base_plugin_id']) {
	    case 'system_branding_block':
	      $variables['site_logo'] = '';
	      if ($variables['content']['site_logo']['#access'] && $variables['content']['site_logo']['#uri']) {
	        $variables['site_logo'] = str_replace('.svg', '.png', $variables['content']['site_logo']['#uri']);
	      }
	    break;
  	}
	if(isset($variables['elements']['#id']) && !empty($variables['elements']['#id'])){
		$block_id = $variables['elements']['#id'];
	  	$block = \Drupal\block\Entity\Block::load($block_id);
	  	if($block->getRegion()){
	  		$region = $block->getRegion();
	  		$variables['region'] = $region;
	  	}
	//config as context module
	}else{
		$variables['region'] = $variables['elements']['#configuration']['region'];
	}

}
function apar_preprocess_html(&$variables){
	global $base_url;
  	$theme = \Drupal::theme()->getActiveTheme()->getName();
  	$variables['general_setting_tracking_code'] = theme_get_setting('general_setting_tracking_code', $theme);
  	$variables['custom_css'] = theme_get_setting('custom_css', $theme);
  	$variables['base_path'] = base_path();
	$variables['theme_path'] = drupal_get_path('theme', $theme);
	$site_name = \Drupal::config('system.site')->get('name');
	$variables['site_name'] = $site_name;
	$apar_theme_path = base_path().drupal_get_path('theme', 'apar');
	$variables['apar_theme_path'] = $apar_theme_path;

  	if(\Drupal::routeMatch()->getParameter('node')){
		$node = \Drupal::routeMatch()->getParameter('node');
		$ntype = $node->getType();
		if($ntype == 'page'){
			$variables['#attached']['library'][] = 'apar/apar-lib-basic';
		}else{
			$variables['#attached']['library'][] = 'apar/apar-lib';
		}
	}else{
		$variables['#attached']['library'][] = 'apar/apar-lib';
	}
	$layout_page = theme_get_setting('layout_page', 'apar');
	if(isset($layout_page) && !empty($layout_page)){
		$variables['layout_page'] = $layout_page;
	}else{
		$variables['layout_page'] = 'wide';
	}

	$skin_pr = theme_get_setting('built_in_skins_pr','apar');
    if(isset($skin_pr) && !empty($skin_pr)){
        $skin_pr = theme_get_setting('built_in_skins_pr','apar');
    }else{
        $skin_pr = 'default';
    }
    $variables['apar_css_skin_pr'] = $skin_pr;

    $skin_sc = theme_get_setting('built_in_skins_sc','apar');
    if(isset($skin_sc) && !empty($skin_sc)){
        $skin_sc = theme_get_setting('built_in_skins_sc','apar');
    }else{
        $skin_sc = 'default';
    }
    $variables['apar_css_skin_sc'] = $skin_sc;
    //Background Color
    $background_color = theme_get_setting('background_color', 'apar');
	if(isset($background_color) && !empty($background_color)){
		$variables['background_color'] = $background_color;
	}
	//Background Css
	$page_bg_css = theme_get_setting('page_bg_css', 'apar');
	if(isset($page_bg_css) && !empty($page_bg_css)){
		$variables['page_bg_css'] = $page_bg_css;
	}
    //Background Image Page
	if(!empty(theme_get_setting('page_image_bg', 'apar'))){
		$variables['page_image_bg'] = $base_url.theme_get_setting('page_image_bg', 'apar');
	}else{
		$variables['page_image_bg'] = '';
	}
	$background_styles = theme_get_setting('background_styles', 'apar');
	if(isset($background_styles) && !empty($background_styles)){
		$variables['background_styles'] = $background_styles;
	}else{
		$variables['background_styles'] = 'image';
	}


}
function apar_preprocess(&$variables){
	global $base_url;
	$theme = \Drupal::theme()->getActiveTheme()->getName();
	$variables['theme_path'] = drupal_get_path('theme', $theme);
	if (\Drupal::routeMatch()->getRouteName() == 'entity.taxonomy_term.canonical') {
	  	$term_id = \Drupal::routeMatch()->getRawParameter('taxonomy_term');
	  	$term = taxonomy_term_load($term_id);
	  	//$term_name = $term_object->get('name')->value;
	  	$vname = $term->vid->getValue()[0]['target_id'];
	  	if($vname == 'blog_categories'){
	  		$variables['vcname'] = $vname;
		}else{
			$variables['vcname'] = $vname;
		}
		$variables['current_term'] = $term;
	}
	//border
	if (isset($_GET['pre'])) {
	    $variables['preloader_style'] = $_GET['pre'];
	}else{
		$variables['preloader_style'] = theme_get_setting('preloader_style', 'apar');
	}
	//Sidebar
	if (isset($_GET['sidebar'])) {
	    $variables['blog_sidebar'] = $_GET['sidebar'];
	    $variables['product_sidebar'] = $_GET['sidebar'];
	}else{
	    $variables['blog_sidebar'] = theme_get_setting('blog_sidebar', 'apar');
	    $variables['product_sidebar'] = theme_get_setting('product_sidebar', 'apar');
	}
	//Layout
	if (isset($_GET['layout'])) {
	    $variables['blog_layout'] = $_GET['layout'];
	    $variables['contact_layout'] = $_GET['layout'];
	    $variables['product_layout'] = $_GET['layout'];
	}else{
	    $variables['blog_layout'] = theme_get_setting('blog_layout', 'apar');
	    $variables['contact_layout'] = theme_get_setting('contact_layout', 'apar');
	    $variables['product_layout'] = theme_get_setting('product_layout', 'apar');
	}
	$variables['header_style'] = theme_get_setting('header_style', 'apar');
	$variables['footer_style'] = theme_get_setting('footer_style', 'apar');
	if ($node = \Drupal::routeMatch()->getParameter('node')) {
	    if (isset($node->field_header_style) && !empty($node->field_header_style->getValue()[0]['value'])) {
	        $variables['header_style'] = $node->field_header_style->getValue()[0]['value'];
	    }
	    if (isset($node->field_footer_style) && !empty($node->field_footer_style->getValue()[0]['value'])) {
	        $variables['footer_style'] = $node->field_footer_style->getValue()[0]['value'];
	    }
	}

	if(\Drupal::routeMatch()->getParameter('node')){
		$node = \Drupal::routeMatch()->getParameter('node');
		$ntype = $node->getType();
		$variables['ntype'] = $ntype;

		if($ntype == 'portfolio'){
			$tids = array();
			$cate_portfolio = array();
			foreach ($node->field_portfolio_categories as $key => $value) {
				$cate_portfolio[$key] = $value->target_id;
			}
			$storage = \Drupal::entityManager()->getStorage('node');
		    $nids = $storage->getQuery()
		        ->condition('type', 'portfolio')
		        ->condition('status', 1)
		        ->condition('nid', $node->nid->value, '!=')
		        ->condition('field_portfolio_categories.target_id', $cate_portfolio, 'in')
		        ->sort('changed','desc')
		        ->range(0,10)
		        ->execute();
		    $related_posts = '';
		    foreach(entity_load_multiple('node',$nids) as $k => $n){
		    	$options = ['absolute' => TRUE];
    			$url_object = \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => $n->nid->value], $options);

				$node_url = $url_object->toString();
				//image
				$fid = $n->field_portfolio_image->getValue()[0]['target_id'];
				$uri = file_load($fid)->uri->value;
			  	$style = ImageStyle::load('image_380x250');
			  	$url = $style->buildUrl($uri);
			  	$url_ori = file_create_url($uri);
			  	$project_by = $n->field_project_by->value;
			  	$portfolio_format = $n->field_portfolio_format->value;
				$portfolio_video = $n->field_video_embed->value;
				$categ = '';
			    foreach($n->field_portfolio_categories as $k => $v):

			    	if($k!=count($n->field_portfolio_categories) - 1):
			    		$categ .= $v->entity->name->value.' / ';
			    	else:
			    		$categ .= $v->entity->name->value;
			    	endif;

			    endforeach;


			  	if($portfolio_format == 'video'){
					$related_link = '<a href="'.$node_url.'" class="cbp-l-caption-buttonLeft" rel="nofollow">more info</a>

				                    <a href="'.$portfolio_video.'" class="cbp-lightbox cbp-l-caption-buttonRight" data-title="'.$n->title->value.'<br>by '.$project_by.'">view video
				                    </a>';
				}else{
					$related_link = '<a href="'.$node_url.'" class="cbp-l-caption-buttonLeft" rel="nofollow">more info</a>

				                    <a href="'.$url_ori.'" class="cbp-lightbox cbp-l-caption-buttonRight" data-title="'.$n->title->value.'<br>by '.$project_by.'">view larger
				                    </a>';
				}
				$related_posts .=   '<div class="cbp-item">
									    <div class="cbp-caption">
									        <div class="cbp-caption-defaultWrap">
									            <img src="'.$url.'" alt="'.$n->title->value.'">
									        </div>
									        <div class="cbp-caption-activeWrap">
									            <div class="cbp-l-caption-alignCenter">
									                <div class="cbp-l-caption-body">
									    				'.$related_link.'
									                </div>
									            </div>
									        </div>
									    </div>
									    <div class="cbp-l-grid-projects-title">'.$n->title->value.'</div>
									    <div class="cbp-l-grid-projects-desc">'.($categ ? $categ : '').'</div>
									</div>';

			}

			$variables['is_exist_rp'] = $nids;
			$variables['related_posts'] = $related_posts;
			//related posts end

		}
	}
	//Header Image
	if(!empty(theme_get_setting('header_image_url', 'apar'))){
		$variables['header_image_url'] = $base_url.theme_get_setting('header_image_url', 'apar');
	}else{
		$variables['header_image_url'] = '';
	}
	//Header Tran logo
	if(!empty(theme_get_setting('header_transparent_logo_url', 'apar'))){
		$variables['header_transparent_logo_url'] = $base_url.theme_get_setting('header_transparent_logo_url', 'apar');
	}else{
		$variables['header_transparent_logo_url'] = '';
	}
	//Header Dark logo
	if(!empty(theme_get_setting('header_dark_logo_url', 'apar'))){
		$variables['header_dark_logo_url'] = $base_url.theme_get_setting('header_dark_logo_url', 'apar');
	}else{
		$variables['header_dark_logo_url'] = '';
	}
	//Page Title Image
	if(!empty(theme_get_setting('page_title_image_url', 'apar'))){
		$variables['page_title_image_url'] = $base_url.theme_get_setting('page_title_image_url', 'apar');
	}else{
		$variables['page_title_image_url'] = '';
	}
	//Footer Background Image
	if(!empty(theme_get_setting('footer_image_url', 'apar'))){
		$variables['footer_image_url'] = $base_url.theme_get_setting('footer_image_url', 'apar');
	}else{
		$variables['footer_image_url'] = '';
	}
	//Contact Background Image
	if(!empty(theme_get_setting('contact_image_url', 'apar'))){
		$variables['contact_image_url'] = $base_url.theme_get_setting('contact_image_url', 'apar');
	}else{
		$variables['contact_image_url'] = '';
	}
	//Maintenance page header bg
	if(!empty(theme_get_setting('maintenance_page_header_bg', 'apar'))){
		$variables['maintenance_page_header_bg'] = $base_url.theme_get_setting('maintenance_page_header_bg', 'apar');
	}else{
		$variables['maintenance_page_header_bg'] = '';
	}
	//Preloader Display
	$display_preloader = theme_get_setting('display_preloader', 'apar');
	if(isset($display_preloader) && !empty($display_preloader)){
		$variables['display_preloader'] = $display_preloader;
	}
	//Switch Display
	$display_switch = theme_get_setting('display_switch', 'apar');
	if(isset($display_switch) && !empty($display_switch)){
		$variables['display_switch'] = $display_switch;
	}
	//title_form
	$title_form = theme_get_setting('title_form', 'apar');
	if(isset($title_form) && !empty($title_form)){
		$variables['title_form'] = $title_form;
	}
	//title_contact
	$title_contact = theme_get_setting('title_contact', 'apar');
	if(isset($title_contact) && !empty($title_contact)){
		$variables['title_contact'] = $title_contact;
	}
	//contact_address
	$contact_address = theme_get_setting('contact_address', 'apar');
	if(isset($contact_address) && !empty($contact_address)){
		$variables['contact_address'] = $contact_address;
	}
	//contact_email
	$contact_email = theme_get_setting('contact_email', 'apar');
	if(isset($contact_email) && !empty($contact_email)){
		$variables['contact_email'] = $contact_email;
	}
	//contact_phone
	$contact_phone = theme_get_setting('contact_phone', 'apar');
	if(isset($contact_phone) && !empty($contact_phone)){
		$variables['contact_phone'] = $contact_phone;
	}
	//contact_fax
	$contact_fax = theme_get_setting('contact_fax', 'apar');
	if(isset($contact_fax) && !empty($contact_fax)){
		$variables['contact_fax'] = $contact_fax;
	}
	//contact_website
	$contact_website = theme_get_setting('contact_website', 'apar');
	if(isset($contact_website) && !empty($contact_website)){
		$variables['contact_website'] = $contact_website;
	}
	//Copyright text
	$copyright_text = theme_get_setting('copyright_text', 'apar');
	if(isset($copyright_text) && !empty($copyright_text)){
		$variables['copyright_text'] = $copyright_text;
	}
	//Social Network Footer
	$social_network_footer = theme_get_setting('social_network_footer', 'apar');
	if(isset($social_network_footer) && !empty($social_network_footer)){
		$variables['social_network_footer'] = $social_network_footer;
	}
	$variables['#cache']['contexts'][] = 'url';


}
function apar_breadcrumb($variables){
	$request = \Drupal::request();
	if ($route = $request->attributes->get(\Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_OBJECT)) {
		$current_title = \Drupal::service('title_resolver')->getTitle($request, $route);
	}
	$breadcrumb = $variables['breadcrumb'];

  	$output = '';
  	if (!empty($breadcrumb)) {
    	foreach ($breadcrumb as $crumb) {
    		if($crumb['url']){
    			$output .= '<a href="'.$crumb['url'].'">'.$crumb['text'].'</a>';

			}else{
				$output .= $crumb['text'];
			}

    	}
    	$output .= '<span>'.render($current_title).'</span>';
  	}
  return $output;
}
function apar_preprocess_page(&$variables) {

	global $base_url, $product_entity;

	$pageURL = 'http';
 	if(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on'){
 		$pageURL .= "s";
 	}
	$pageURL .= '://';
 	if($_SERVER['SERVER_PORT'] != '80'){
  	$pageURL .= $_SERVER['SERVER_NAME'].":".$_SERVER['SERVER_PORT'].$_SERVER['REQUEST_URI'];
 	}else{
  		$pageURL .= $_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'];
 	}
 	$variables['pageURL'] = $pageURL;
	$config = \Drupal::config('system.site');
  	$variables['site_name'] = $config->get('name');
	$request = \Drupal::request();

	if ($route = $request->attributes->get(\Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_OBJECT)) {
		$variables['title'] = \Drupal::service('title_resolver')->getTitle($request, $route);
	}
    if(\Drupal::routeMatch()->getParameter('node')){
		$node = \Drupal::routeMatch()->getParameter('node');
		$ntype = $node->getType();
	}


	if (!empty($product_entity)){
		$variables['product_entity'] = $product_entity;
	}

	// related_products
	if (\Drupal::routeMatch()->getParameter('commerce_product')) {
	    $commerce_product = \Drupal::routeMatch()->getParameter('commerce_product');
	    $current_product_sidebar = $commerce_product->field_product_sidebar->value;
	    $current_product_id = $commerce_product->product_id->value;
	    $current_product_categories_id = array();
	    foreach ($commerce_product->field_product_categories as $key => $value) {
	        $current_product_categories_id[$key] = $value->target_id;
	    }
	    $storage = \Drupal::entityTypeManager()->getStorage('commerce_product');
	    //kint($storage);
	    if ($current_product_sidebar == 'left' || $current_product_sidebar == 'right'){
	    	$number_it_rl = '3';
	    }else{
	    	$number_it_rl = '4';
	    }
	    $pids = $storage->getQuery()
	            ->condition('type', 'default')
	            ->condition('status', 1)
	            ->condition('product_id', $current_product_id, '!=')
	            ->condition('field_product_categories.target_id', $current_product_categories_id, 'in')
	            ->sort('created', 'DESC')
	            ->range(0, $number_it_rl)
	            ->execute();
	    if ($pids) {
	        $output = array();

	        $i = 0;
	        foreach (entity_load_multiple('commerce_product', $pids) as $key => $pd) {
	        	//kint($pd->field_price_old);
	        	$field_price_old_build = $pd->field_price_old->view('related_products');
	        	$field_price_old = \Drupal::service('renderer')->renderRoot($field_price_old_build);
	        	$field_price_old_striptags = strip_tags($field_price_old);
	            $price_old_pd = trim($field_price_old_striptags);

	        	//kint($field_price_old);
	            $pd_id = $pd->product_id->value;
	            $options = ['absolute' => TRUE];
	            $url_object = \Drupal\Core\Url::fromRoute('entity.commerce_product.canonical', ['commerce_product' => $pd_id], $options);

	            //add to cart
	            $build_addtocart = $pd->variations->view('default');
	            $addtocart_btn = \Drupal::service('renderer')->renderRoot($build_addtocart);
	            // $addtocart_btn_class = $addtocart_btn.addClass("btn btn-border light btn-small");
	            //$addtocart_btn = str_replace('', '', '');
	            //images
	            $pd_summary = $pd->body->summary;
	            $build_product_image = $pd->field_product_image->view('default');
	            if ($build_product_image['#items'][0]) {
	                $pd_imageone_uri = $build_product_image['#items']->entity->uri->value;
	            } else {
	                $pd_imageone_uri = '';
	            }
	            if (isset($pd_imageone_uri) && !empty($pd_imageone_uri)) {
	                $style = ImageStyle::load('image_600x700');
	                if($style){
	                    $url = $style->buildUrl($pd_imageone_uri);
	                    $pd_imageone_url_image = $url;
	                }
	            } else {
	                $pd_imageone_url_image = '';
	            }
	            //variation price
	            $variations_build = $pd->variations->view('related_products');
	            $variation_price_el = \Drupal::service('renderer')->renderRoot($variations_build);
	            $variation_price_striptags = strip_tags($variation_price_el);
	            $variation_price = trim($variation_price_striptags);
	            if(isset($pd->field_price_old) && !empty($price_old_pd)){
					$price = '<span><del>'.$price_old_pd.'</del></span><span class="text-dark"> '.($variation_price ? $variation_price : '').'</span>';
				}else{
					$price = '<span class="text-dark"> '.($variation_price ? $variation_price : '').'</span>';
				}
	            if ($current_product_sidebar == 'left' || $current_product_sidebar == 'right'){
	            	$output[$i] = '<div class="col-md-4 col-sm-6 col-xs-12 pd-rl-item">
								    <div class="sp-feature-box-3 margin-bottom">
								        <div class="img-box">
								            <a href="'.$url_object->toString().'" class="view-btn uppercase">View</a>
								            <img src="'.$pd_imageone_url_image.'" alt="'.$pd->title->value.'" class="img-responsive"/>
								        </div>
								        <div class="clearfix"></div>
								        <br/>
								        <h5 class="less-mar-1">'.$pd->title->value.'</h5>
								        <p>'.$pd_summary.'</p>
								        <h5 class="text-gyellow">'.($variation_price ? $variation_price : '').'</h5>
								        <br/>
								        '.($addtocart_btn ? $addtocart_btn : '').'
								    </div>
								</div>';
	            }elseif ($current_product_sidebar == 'none'){
	            	$output[$i] = '<div class="col-md-3 col-sm-6 col-xs-12 pd-rl-item">
								    <div class="sp-feature-box-3 margin-bottom">
								        <div class="img-box">
								            <a href="'.$url_object->toString().'" class="view-btn uppercase">View</a>
								            <img src="'.$pd_imageone_url_image.'" alt="'.$pd->title->value.'" class="img-responsive"/>
								        </div>
								        <div class="clearfix"></div>
								        <br/>
								        <h5 class="less-mar-1">'.$pd->title->value.'</h5>
								        <p>'.$pd_summary.'</p>
								        <h5 class="text-gyellow">'.($variation_price ? $variation_price : '').'</h5>
								        <br/>
								        '.($addtocart_btn ? $addtocart_btn : '').'
								    </div>
								</div>';
	            }else{
	            	$output[$i] = '<div class="col-md-3 col-sm-12 col-xs-12 nopadding apar-item-rl-margin-bottom">
		                                <div class="imgbox-small left"> <img src="'.$pd_imageone_url_image.'" alt="'.$pd->title->value.'" class="img-responsive"/></div>
		                                <div class="text-box-right">
		                                    <h6 class="uppercase nopadding"><a href="'.$url_object->toString().'" class="text-hover-gyellow">'.$pd->title->value.'</a></h6>
		                                    <div class="blog-post-info fs-more padding-top-1">'.$price.'</div>
		                                </div>
		                            </div>';
	            }
	            //$output[$i] = $url_object->toString();

	            $i++;
	        }
	        $variables['related_products'] = $output;
	    }

	}
	if (\Drupal::routeMatch()->getRouteName() == 'entity.taxonomy_term.canonical') {
	    $term_id = \Drupal::routeMatch()->getRawParameter('taxonomy_term');
	    $term = taxonomy_term_load($term_id);
	    //$term_name = $term_object->get('name')->value;
	    //$vname = $term->vid->getValue()[0]['target_id'];
	    //$variables['current_term_view'] = $term;

	    $vv = $term->vid->getValue();
	    $vp = $vv[0];
	    $vn = $vp['target_id'];
	    $vname = $vn;
	    $variables['v_name'] = $vname;
	    $current_term_id = $term_id;

	    /**************************PRODUCTS*********************/

	    $storage = \Drupal::entityTypeManager()->getStorage('commerce_product');

	    if(isset($_GET['page']) && is_numeric($_GET['page'])){
	        $page = $_GET['page'];
	    }else{
	        $page = 0;
	    }

	    //-----------Config pager---------///
	    if(theme_get_setting('','apar') && theme_get_setting('product_page_taxonomy_items_per_page','apar') > 0){
	        $number_rows_per_page = theme_get_setting('product_page_taxonomy_items_per_page','apar');
	    }else{
	        $number_rows_per_page = 1;
	    }
	    if($vname == 'product_categories'){
	        //count rows
	        $pids_rows = $storage->getQuery()
	                ->condition('type', 'default')
	                ->condition('status', 1)
	                //->condition('product_id', $current_product_id, '!=')
	                ->condition('field_product_categories.target_id', $current_term_id, 'in')
	                ->sort('created','DESC')
	                ->execute();
	        $count_pids_rows = count($pids_rows);
	        $pids = $storage->getQuery()
	                ->condition('type', 'default')
	                ->condition('status', 1)
	                //->condition('product_id', $current_product_id, '!=')
	                ->condition('field_product_categories.target_id', $current_term_id, 'in')
	                ->sort('created','DESC')
	                ->range($page * $number_rows_per_page, $number_rows_per_page)
	                ->execute();
	    }elseif($vname == 'product_tags'){
	        //count rows
	        $pids_rows = $storage->getQuery()
	                ->condition('type', 'default')
	                ->condition('status', 1)
	                //->condition('product_id', $current_product_id, '!=')
	                ->condition('field_product_tags.target_id', $current_term_id, 'in')
	                ->sort('created','DESC')
	                ->execute();
	        $count_pids_rows = count($pids_rows);
	        $pids = $storage->getQuery()
	                ->condition('type', 'default')
	                ->condition('status', 1)
	                //->condition('product_id', $current_product_id, '!=')
	                ->condition('field_product_tags.target_id', $current_term_id, 'in')
	                ->sort('created','DESC')
	                ->range($page * $number_rows_per_page, $number_rows_per_page)
	                ->execute();
	    }else{
	        $pids = '';
	        $count_pids_rows = 0;
	    }
	    if(isset($pids) && !empty($pids)){

	        $product_array = array();
	        $i = 0;
	        //$shop_catalog_style = $variables['shop_catalog_style'];
	        foreach (entity_load_multiple('commerce_product', $pids) as $key => $pd) {
	            $pd_id = $pd->product_id->value;
	            $options = ['absolute' => TRUE];
	            $url_object = \Drupal\Core\Url::fromRoute('entity.commerce_product.canonical', ['commerce_product' =>$pd_id], $options);

	            //add to cart
	            $build_addtocart = $pd->variations->view('default');
	            $addtocart_btn = \Drupal::service('renderer')->renderRoot($build_addtocart);
	            //$addtocart_btn = str_replace('', '', '');
	            //images
	            $pd_summary = $pd->body->summary;
	            $build_product_image = $pd->field_product_image->view('default');
	            if ($build_product_image['#items'][0]) {
	                $pd_imageone_uri = $build_product_image['#items']->entity->uri->value;
	            } else {
	                $pd_imageone_uri = '';
	            }
	            if (isset($pd_imageone_uri) && !empty($pd_imageone_uri)) {
	                $style = ImageStyle::load('image_600x700');
	                if($style){
	                    $url = $style->buildUrl($pd_imageone_uri);
	                    $pd_imageone_url_image = $url;
	                }
	            } else {
	                $pd_imageone_url_image = '';
	            }
	            //variation price
	            $variations_build = $pd->variations->view('related_products');
	            $variation_price_el = \Drupal::service('renderer')->renderRoot($variations_build);
	            $variation_price_striptags = strip_tags($variation_price_el);
	            $variation_price = trim($variation_price_striptags);
	            $product_array[$i] = '<div class="col-md-4 col-sm-6 col-xs-12 pd-list-item">
	                                    <div class="sp-feature-box-3 margin-bottom">
	                                        <div class="img-box">
	                                            <a href="'.$url_object->toString().'" class="view-btn uppercase">View</a>
	                                            <img src="'.$pd_imageone_url_image.'" alt="'.$pd->title->value.'" class="img-responsive"/>
	                                        </div>
	                                        <div class="clearfix"></div>
	                                        <br/>
	                                        <h5 class="less-mar-1">'.$pd->title->value.'</h5>
	                                        <p>'.$pd_summary.'</p>
	                                        <h5 class="text-gyellow">'.($variation_price ? $variation_price : '').'</h5>
	                                        <br/>
	                                        '.($addtocart_btn ? $addtocart_btn : '').'
	                                    </div>
	                                </div>';

	            //$output[$i] = $url_object->toString();

	            $i++;
	        }
	        if(isset($product_array) && !empty($product_array)){
	            $variables['product_taxonomy_term_content'] = $product_array;
	        }

	        //********************************** Pager Starts ********************************************/
	        global $base_path;
	        $variables['trust_current_path'] = $base_path;
	        if($number_rows_per_page < $count_pids_rows){

	            $number_page = $count_pids_rows / $number_rows_per_page;
	            $number_page = ceil($number_page);
	            $product_txnm_pager = '<div class="col-md-12"><ul class="blog-pagenation">';
	            //first page
	            if($page != 0){
	                $product_txnm_pager .= '<li><a href="'.$variables['trust_current_path'].'?page=0" title="'.t('Go to first page').'"><i class="fa fa-angle-double-left"></i></a></li>';
	            }
	            //previous page
	            if($page > 0){
	                $product_txnm_pager .= '<li><a href="?page='.($page - 1).'" title="'.t('Go to previous page').'"><i class="fa fa-angle-left"></i></a></li>';
	            }

	            //page items
	            for($i = 0; $i < $number_page; $i++){

	                $product_txnm_pager .= '<li><a class="'.($page == $i ? 'page-numbers current active' : '').'" href="'.($page == $i ? '#' : '?page='.$i).'" title="'.($page == $i ? t('Current page') : t('Go to page '.($i+1).'')).'">'.($i+1).'</a></li>';

	            }
	            //next page
	            if($page >= 0 && $page < $number_page - 1){
	                $product_txnm_pager .= '<li><a href="?page='.($page + 1).'" title="'.t('Go to next page').'"><i class="fa fa-angle-right"></i></a></li>';
	            }
	            //last page
	            if($page != $number_page - 1){
	                $product_txnm_pager .= '<li><a href="'.$variables['trust_current_path'].'?page='.($number_page - 1).'" title="'.t('Go to last page').'"><i class="fa fa-angle-double-right"></i></a></li>';
	            }


	            $product_txnm_pager .= '</ul></div>';
	        }
	        /*********************************** Pager Ends *********************************************/


	        //pager
	        if(isset($product_txnm_pager) && !empty($product_txnm_pager)){
	            $variables['product_txnm_pager'] = $product_txnm_pager;
	        }


	    }
	    /************************PRODUCTs ENDS*******************/

	}
	$variables['#attached']['drupalSettings']['path']['themeUrl'] = base_path().\Drupal::theme()->getActiveTheme()->getPath();
}
function apar_preprocess_node(&$variables) {
	global $base_url;

	$site_name = \Drupal::config('system.site')->get('name');
	$variables['site_name'] = $site_name;
	$request = \Drupal::request();
	if ($route = $request->attributes->get(\Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_OBJECT)) {
		$variables['title'] = \Drupal::service('title_resolver')->getTitle($request, $route);
	}
	$pageURL = 'http';
 	if(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on'){
 		$pageURL .= "s";
 	}
	$pageURL .= '://';
 	if($_SERVER['SERVER_PORT'] != '80'){
  	$pageURL .= $_SERVER['SERVER_NAME'].":".$_SERVER['SERVER_PORT'].$_SERVER['REQUEST_URI'];
 	}else{
  		$pageURL .= $_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'];
 	}
 	$variables['pageURL'] = $pageURL;
 	if(\Drupal::routeMatch()->getParameter('node')){
		$node = \Drupal::routeMatch()->getParameter('node');
		$ntype = $node->getType();

	}

}
function apar_preprocess_container(&$variables){
	$variables['container_type'] = $variables['element']['#type'];
}
function apar_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	//kint($form_id);
  	if($form_id == 'search_block_form'){
  		//kint($form);
	  	//unset($form['search_block_form']['#title']); // remove label form
	    unset($form['actions']['submit']['#value']);
	    $form['keys']['#attributes']['placeholder'] = 'Search';

	    //print_r($form);
    }elseif(preg_match("/simplenews_subscriptions_block/", $form_id)){
	   	$form['actions']['subscribe']['#attributes']['class'] = array('btn');
	   	$form['actions']['unsubscribe']['#attributes']['class'] = array('btn');
	   	$form['actions']['update']['#attributes']['class'] = array('btn');
	   	$form['mail']['widget'][0]['value']['#placeholder'] = t('Subscribe');
	   	$form['mail']['widget'][0]['value']['#attributes']['placeholder'] = t('Enter Your Email');
	   	unset($form['mail']['widget'][0]['value']['#description']);
	   	unset($form['mail']['widget'][0]['value']['#title']);
    }elseif(preg_match("/user_login_form/", $form_id)){
    	//kint($form);
    	$form['name']['#prefix'] = '<div class="field prepend-icon">';
		$form['name']['#suffix'] = '<span class="field-icon"><i class="fa fa-user"></i></span></div>';
    	$form['name']['#attributes']['class']= array('gui-input');
    	$form['name']['#attributes']['placeholder']= t('Enter username');
    	unset($form['name']['#title']);
    	$form['pass']['#attributes']['class']= array('gui-input');
    	$form['pass']['#prefix'] = '<div class="field prepend-icon">';
		$form['pass']['#suffix'] = '<span class="field-icon"><i class="fa fa-lock"></i></span></div>';
    	$form['pass']['#attributes']['placeholder']= t('Enter password');
    	unset($form['pass']['#title']);
    	$form['actions']['#prefix'] = '<div class="form-footer">';
		$form['actions']['#suffix'] = '</div>';
    	$form['actions']['submit']['#attributes']['class'] = array('button', 'btn-primary');
    }elseif(preg_match("/user_register_form/", $form_id)){
    	//kint($form);
    	$form['account']['name']['#attributes']['class']= array('gui-input');
    	//$form['account']['name']['#prefix'] = '<div class="field prepend-icon">';
			//$form['account']['name']['#suffix'] = '<span class="field-icon"><i class="fa fa-user"></i></span></div>';
    	$form['account']['name']['#attributes']['placeholder']= t('Enter username');
    	$form['account']['mail']['#attributes']['class']= array('gui-input');
    	$form['account']['mail']['#prefix'] = '<div class="field prepend-icon">';
		$form['account']['mail']['#suffix'] = '<span class="field-icon"><i class="fa fa-envelope"></i></span></div>';
    	$form['account']['mail']['#attributes']['placeholder']= t('example@domain.com...');

    	// $form['field_full_name']['widget'][0]['value']['#attributes']['class'] = array('form-control');
    	$form['actions']['#prefix'] = '<div class="form-footer">';
		$form['actions']['#suffix'] = '</div>';
    	$form['actions']['submit']['#attributes']['class'] = array('button', 'btn-primary');
    }elseif(preg_match("/user_pass/", $form_id)){
    	$form['name']['#attributes']['class']= array('gui-input');
    	$form['name']['#attributes']['placeholder']= t('Enter username or Email');
    	$form['actions']['#prefix'] = '<div class="form-footer">';
		$form['actions']['#suffix'] = '</div>';
    	$form['actions']['submit']['#attributes']['class'] = array('button', 'btn-primary');
    }elseif(preg_match("/search_form/", $form_id)){
    	$form['basic']['keys']['#attributes']['class'] = array('form-control');
    	$form['advanced']['keywords-fieldset']['keywords']['or']['#attributes']['class'] = array('form-control');
    	$form['advanced']['keywords-fieldset']['keywords']['phrase']['#attributes']['class'] = array('form-control');
    	$form['advanced']['keywords-fieldset']['keywords']['negative']['#attributes']['class'] = array('form-control');
    	$form['basic']['submit']['#attributes']['class'] = array('btn', 'btn-medium', 'btn-grey', 'btn-3d', 'xround-1', 'uppercase');
    	$form['advanced']['submit']['#attributes']['class'] = array('btn', 'btn-medium', 'btn-grey', 'btn-3d', 'xround-1', 'uppercase');
    }
    if(preg_match('/views_exposed_form/i', $form_id)){
        $form['actions']['submit']['#attributes']['class'] = array('hidden');
        $form['sort_by']['#attributes']['onchange'] = 'if(this.value != 0) { this.form.submit(); }';
    }

}
function apar_form_comment_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
	//kint($form['field_comment_body']['widget']);
	$form['subject']['widget'][0]['value']['#attributes']['class'] = array('bg-cinput');
	$form['subject']['widget'][0]['value']['#attributes']['placeholder'] = t('Title');
	$form['author']['name']['#attributes']['placeholder'] = t('Enter Name');
	$form['author']['name']['#attributes']['class'] = array('bg-cinput');

	$form['field_email_comment']['widget'][0]['value']['#placeholder'] = t('Email Address');
	$form['field_email_comment']['widget'][0]['value']['#attributes']['class'] = array('bg-cinput');
	$form['field_comment_body']['widget'][0]['value']['#placeholder'] = t('Your Message');
	$form['field_comment_body']['widget'][0]['value']['#attributes']['class'] = array('bg-ctexteria');
	$form['actions']['submit']['#attributes']['class'] = array('btn', 'btn-dark-3', 'btn-large', 'uppercase');
	$form['actions']['submit']['#attributes']['value'] = t('Post Comments');

	unset($form['subject']['widget'][0]['value']['#title']);
	unset($form['author']['name']['#title']);
	unset($form['field_email_comment']['widget'][0]['value']['#title']);
	unset($form['field_comment_body']['widget'][0]['value']['#title']);
	unset($form['actions']['preview']);
	//kint($form['field_comment_body']);
}
function apar_form_contact_message_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
	//kint($form['field_phone']);
	unset($form['subject']['widget'][0]['value']['#title']);
	$form['subject']['#prefix'] = '<div class="field prepend-icon">';
	$form['subject']['#suffix'] = '<span class="field-icon"><i class="fa fa-lightbulb-o"></i></span></div>';
	$form['subject']['widget'][0]['value']['#attributes']['placeholder'] = t('Enter subject');
	$form['subject']['widget'][0]['value']['#attributes']['class'] = array('gui-input');
	unset($form['message']['widget'][0]['value']['#title']);
	$form['message']['#prefix'] = '<div class="field prepend-icon">';
	$form['message']['#suffix'] = '<span class="field-icon"><i class="fa fa-comments"></i></span></div>';
	$form['message']['widget'][0]['value']['#attributes']['placeholder'] = t('Enter Message');
	$form['message']['widget'][0]['value']['#attributes']['class'] = array('gui-textarea');
	unset($form['mail']['#title']);
	$form['mail']['#prefix'] = '<div class="field prepend-icon">';
	$form['mail']['#suffix'] = '<span class="field-icon"><i class="fa fa-envelope"></i></span></div>';
	$form['mail']['#attributes']['placeholder'] = t('Email address');
	$form['mail']['#attributes']['class'] = array('gui-input');
	unset($form['name']['#title']);
	$form['name']['#prefix'] = '<div class="field prepend-icon">';
	$form['name']['#suffix'] = '<span class="field-icon"><i class="fa fa-user"></i></span></div>';
	$form['name']['#attributes']['placeholder'] = t('Enter name');
	$form['name']['#attributes']['class'] = array('gui-input');
	unset($form['field_phone']['widget'][0]['value']['#title']);
	$form['field_phone']['#prefix'] = '<div class="field prepend-icon">';
	$form['field_phone']['#suffix'] = '<span class="field-icon"><i class="fa fa-phone-square"></i></span></div>';
	$form['field_phone']['widget'][0]['value']['#attributes']['class'] = array('gui-input');
	$form['field_phone']['widget'][0]['value']['#attributes']['placeholder'] = t('Enter Telephone...');
	//$form['field_phone']['#attributes']['class'] = array('form-control', 'form-value');
	unset($form['actions']['preview']);
	$form['actions']['submit']['#attributes']['class'] = array('btn', 'btn-primary');
	$form['actions']['submit']['#attributes']['value'] = t('Submit');

}
// function apar_form_uc_cart_view_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
// 	//kint($form);
// 	foreach($form['items'] as $k => $v){
// 		if(is_numeric($k)){
// 			$form['items'][$k]['remove']['#attributes']['class'] = array('button', 'btn', 'btn-default');
// 		}
// 	}
// 	//$form['actions']['checkout']['#attributes']['class'] = array('');
// 	//unset($form['items']['#footer']);
// 	unset($form['actions']['continue_shopping']);
// 	$form['actions']['update']['#attributes']['class'] = array('button', 'btn', 'btn-default');
// 	$form['actions']['checkout']['checkout']['#attributes']['class'] = array('button', 'btn', 'btn-default');
// 	//$form['actions']['checkout']['checkout']['#attributes']['id'] = t('cart-checkout-comets');
// }
// function apar_form_uc_cart_checkout_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
// 	//kint($form['panes']['billing']);
// 	$form['actions']['continue']['#attributes']['class'] =  array('btn', 'btn-color');
// 	$form['actions']['cancel']['#attributes']['class'] = array('btn', 'btn-dark');

// }
// function apar_preprocess_uc_cart_block(&$variables){
// 	global $base_url;

// 	$arr_image = array();
// 	$arr_alt = array();
// 	foreach($variables['items'] as $k => $n){
// 		$node = node_load($n['nid']);
//     	$fid = $node->uc_product_image->getValue()[0]['target_id'];
// 		$uri = file_load($fid)->uri->value;
// 		$style = ImageStyle::load('image_100x100');
// 		$url = $style->buildUrl($uri);
// 		$arr_image[$k] = $url;
// 		$alt = $node->uc_product_image->getValue()[0]['alt'];
// 		$arr_alt[$k] = $alt;

// 	}
// 	if(isset($arr_image) && !empty($arr_image)){
// 		$variables['arr_image'] = $arr_image;
// 	}else{
// 		$variables['arr_image'] = '';
// 	}
// 	if(isset($arr_alt) && !empty($arr_alt)){
// 		$variables['arr_alt'] = $arr_alt;
// 	}else{
// 		$variables['arr_alt'] = '';
// 	}

// 	$str = render($variables['summary_links'])->__toString();
// 	$variables['summary_links_cs'] = strip_tags($str,'<a>');


// }
// function apar_form_uc_product_add_to_cart_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
// 	unset($form['actions']['submit']['#id']);
// 	$form['#attributes']['class'] = array('inline-form');
// 	$form['qty']['#attributes']['class'] = array('form-control');
// 	$form['actions']['submit']['#attributes']['class'] = array('button', 'btn' , 'btn-default');
// 	unset($form['qty']['#title']);
// }
function apar_preprocess_commerce_product(&$variables){
	//kint($variables);
	$pageURL = 'http';
 	if(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on'){
 		$pageURL .= "s";
 	}
	$pageURL .= '://';
 	if($_SERVER['SERVER_PORT'] != '80'){
  	$pageURL .= $_SERVER['SERVER_NAME'].":".$_SERVER['SERVER_PORT'].$_SERVER['REQUEST_URI'];
 	}else{
  		$pageURL .= $_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'];
 	}
 	$variables['pageURL'] = $pageURL;

	global $product_entity;
	if(isset($variables['product_entity'])){
		$product_entity = $variables['product_entity'];
	}
}
