---
- name: Ensure Composer is installed
  ansible.builtin.apt:
    name: "{{ composer_package }}"
    state: present
    update_cache: true

- name: Create symbolic link for Drush
  ansible.builtin.file:
    src: "{{ deployment_root }}/vendor/bin/drush"
    dest: /usr/local/bin/drush
    state: link
    force: true
