---
# Usa a variável de ambiente DEPLOY_SUDO_PASSWORD se disponível
# Caso contrário, usa ansible_become_password_vault do vault
ansible_become_password: "{{ lookup('env', 'DEPLOY_SUDO_PASSWORD') | default(ansible_become_password_vault, true) }}"

