<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bazinga.oauth.provider.token_provider' shared service.

return $this->services['bazinga.oauth.provider.token_provider'] = new \Bazinga\OAuthServerBundle\Doctrine\Provider\TokenProvider(${($_ = isset($this->services['bazinga.oauth.entity_manager']) ? $this->services['bazinga.oauth.entity_manager'] : $this->load('getBazinga_Oauth_EntityManagerService.php')) && false ?: '_'}, 'Mautic\\ApiBundle\\Entity\\oAuth1\\RequestToken', 'Mautic\\ApiBundle\\Entity\\oAuth1\\AccessToken');
