<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bazinga.oauth.signature.hmac_sha1' shared service.

return $this->services['bazinga.oauth.signature.hmac_sha1'] = new \Bazinga\OAuthServerBundle\Service\Signature\OAuthHmacSha1Signature();
