<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bazinga.oauth.signature.plaintext' shared service.

return $this->services['bazinga.oauth.signature.plaintext'] = new \Bazinga\OAuthServerBundle\Service\Signature\OAuthPlainTextSignature();
