<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Mautic\InstallBundle\Configurator\Form\CheckStepType' shared service.

return $this->services['Mautic\\InstallBundle\\Configurator\\Form\\CheckStepType'] = new \Mautic\InstallBundle\Configurator\Form\CheckStepType();
