<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debril.provider.default' shared service.

return $this->services['debril.provider.default'] = new \Debril\RssAtomBundle\Provider\MockProvider();
