<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debril.formatter.atom' shared service.

return $this->services['debril.formatter.atom'] = new \Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter();
