<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debril.http.guzzle_bridge' shared service.

return $this->services['debril.http.guzzle_bridge'] = new \Debril\RssAtomBundle\Driver\GuzzleBridgeDriver();
