<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debril.file' shared service.

return $this->services['debril.file'] = new \Debril\RssAtomBundle\Driver\FileDriver();
