<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debril.formatter.rss' shared service.

return $this->services['debril.formatter.rss'] = new \Debril\RssAtomBundle\Protocol\Formatter\FeedRssFormatter();
