<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Mautic\CoreBundle\Form\Validator\Constraints\FileEncodingValidator' shared service.

return $this->services['Mautic\\CoreBundle\\Form\\Validator\\Constraints\\FileEncodingValidator'] = new \Mautic\CoreBundle\Form\Validator\Constraints\FileEncodingValidator(${($_ = isset($this->services['mautic.lead.model.list']) ? $this->services['mautic.lead.model.list'] : $this->getMautic_Lead_Model_ListService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.field.alias']) ? $this->services['mautic.helper.field.alias'] : $this->load('getMautic_Helper_Field_AliasService.php')) && false ?: '_'});
