<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory_ordered_form.form_extension' shared service.

return $this->services['ivory_ordered_form.form_extension'] = new \Ivory\OrderedForm\Extension\OrderedFormExtension();
