<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_serializer.iterator_handler' shared service.

return $this->services['jms_serializer.iterator_handler'] = new \JMS\Serializer\Handler\IteratorHandler();
