<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_serializer.type_parser' shared service.

return $this->services['jms_serializer.type_parser'] = new \JMS\Serializer\Type\Parser();
