<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_serializer.datetime_handler' shared service.

return $this->services['jms_serializer.datetime_handler'] = new \JMS\Serializer\Handler\DateHandler('c', 'UTC', true);
