<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_menu.templating.helper' shared service.

return $this->services['knp_menu.templating.helper'] = new \Knp\Bundle\MenuBundle\Templating\Helper\MenuHelper(${($_ = isset($this->services['knp_menu.helper']) ? $this->services['knp_menu.helper'] : $this->load('getKnpMenu_HelperService.php')) && false ?: '_'}, ${($_ = isset($this->services['knp_menu.matcher']) ? $this->services['knp_menu.matcher'] : $this->load('getKnpMenu_MatcherService.php')) && false ?: '_'}, ${($_ = isset($this->services['knp_menu.manipulator']) ? $this->services['knp_menu.manipulator'] : ($this->services['knp_menu.manipulator'] = new \Knp\Menu\Util\MenuManipulator())) && false ?: '_'});
