<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.credential.credential_store_factory' shared service.

return $this->services['lightsaml.credential.credential_store_factory'] = new \LightSaml\Store\Credential\Factory\CredentialFactory();
