<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.store.request' shared service.

return $this->services['lightsaml.store.request'] = new \LightSaml\Store\Request\RequestStateSessionStore(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'}, 'main', 'saml_request_state_');
