<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.service.assertion_time_validator' shared service.

return $this->services['lightsaml.service.assertion_time_validator'] = new \LightSaml\Validator\Model\Assertion\AssertionTimeValidator();
