<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.service.subject_validator' shared service.

return $this->services['lightsaml.service.subject_validator'] = new \LightSaml\Validator\Model\Subject\SubjectValidator(${($_ = isset($this->services['lightsaml.service.name_id_validator']) ? $this->services['lightsaml.service.name_id_validator'] : ($this->services['lightsaml.service.name_id_validator'] = new \LightSaml\Validator\Model\NameId\NameIdValidator())) && false ?: '_'});
