<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.system.logger' shared service.

return $this->services['lightsaml.system.logger'] = new \Psr\Log\NullLogger();
