<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.container.party' shared service.

return $this->services['lightsaml.container.party'] = new \LightSaml\SymfonyBridgeBundle\Bridge\Container\PartyContainer(${($_ = isset($this->services['lightsaml.party.idp_entity_descriptor_store']) ? $this->services['lightsaml.party.idp_entity_descriptor_store'] : $this->load('getLightsaml_Party_IdpEntityDescriptorStoreService.php')) && false ?: '_'}, ${($_ = isset($this->services['lightsaml.party.sp_entity_descriptor_store']) ? $this->services['lightsaml.party.sp_entity_descriptor_store'] : ($this->services['lightsaml.party.sp_entity_descriptor_store'] = new \LightSaml\Store\EntityDescriptor\CompositeEntityDescriptorStore())) && false ?: '_'}, ${($_ = isset($this->services['lightsaml.party.trust_options_store']) ? $this->services['lightsaml.party.trust_options_store'] : $this->load('getLightsaml_Party_TrustOptionsStoreService.php')) && false ?: '_'});
