<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.service.endpoint_resolver.descriptor_type' shared service.

return $this->services['lightsaml.service.endpoint_resolver.descriptor_type'] = new \LightSaml\Resolver\Endpoint\DescriptorTypeEndpointResolver();
