<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.container.own' shared service.

return $this->services['lightsaml.container.own'] = new \LightSaml\SymfonyBridgeBundle\Bridge\Container\OwnContainer(${($_ = isset($this->services['lightsaml.own.entity_descriptor_provider']) ? $this->services['lightsaml.own.entity_descriptor_provider'] : $this->load('getLightsaml_Own_EntityDescriptorProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['lightsaml.own.credential_store']) ? $this->services['lightsaml.own.credential_store'] : $this->load('getLightsaml_Own_CredentialStoreService.php')) && false ?: '_'}, $this->getEnv('MAUTIC_SAML_ENTITY_ID'));
