<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.system.time_provider' shared service.

return $this->services['lightsaml.system.time_provider'] = new \LightSaml\Provider\TimeProvider\SystemTimeProvider();
