<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml_sp.attribute_mapper.simple' shared service.

return $this->services['lightsaml_sp.attribute_mapper.simple'] = new \LightSaml\SpBundle\Security\User\SimpleAttributeMapper();
