<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.system.event_dispatcher' shared service.

return $this->services['lightsaml.system.event_dispatcher'] = new \Symfony\Component\EventDispatcher\EventDispatcher();
