<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.party.idp_entity_descriptor_store' shared service.

$this->services['lightsaml.party.idp_entity_descriptor_store'] = $instance = new \LightSaml\Store\EntityDescriptor\CompositeEntityDescriptorStore();

$instance->add(${($_ = isset($this->services['mautic.security.saml.entity_descriptor_store']) ? $this->services['mautic.security.saml.entity_descriptor_store'] : $this->load('getMautic_Security_Saml_EntityDescriptorStoreService.php')) && false ?: '_'});

return $instance;
