<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.credential.credential_store' shared service.

return $this->services['lightsaml.credential.credential_store'] = ${($_ = isset($this->services['lightsaml.credential.credential_store_factory']) ? $this->services['lightsaml.credential.credential_store_factory'] : ($this->services['lightsaml.credential.credential_store_factory'] = new \LightSaml\Store\Credential\Factory\CredentialFactory())) && false ?: '_'}->buildFromOwnCredentialStore(${($_ = isset($this->services['lightsaml.party.idp_entity_descriptor_store']) ? $this->services['lightsaml.party.idp_entity_descriptor_store'] : $this->load('getLightsaml_Party_IdpEntityDescriptorStoreService.php')) && false ?: '_'}, ${($_ = isset($this->services['lightsaml.party.sp_entity_descriptor_store']) ? $this->services['lightsaml.party.sp_entity_descriptor_store'] : ($this->services['lightsaml.party.sp_entity_descriptor_store'] = new \LightSaml\Store\EntityDescriptor\CompositeEntityDescriptorStore())) && false ?: '_'}, $this->getEnv('MAUTIC_SAML_ENTITY_ID'), ${($_ = isset($this->services['lightsaml.own.credential_store']) ? $this->services['lightsaml.own.credential_store'] : $this->load('getLightsaml_Own_CredentialStoreService.php')) && false ?: '_'}, []);
