<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml_sp.username_mapper.simple' shared service.

return $this->services['lightsaml_sp.username_mapper.simple'] = new \LightSaml\SpBundle\Security\User\SimpleUsernameMapper([0 => 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress', 1 => 'http://schemas.xmlsoap.org/claims/EmailAddress', 2 => 'http://schemas.xmlsoap.org/claims/CommonName', 3 => 'http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname', 4 => 'urn:oid:0.9.2342.19200300.100.1.3', 5 => 'uid', 6 => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6', 7 => '@name_id@']);
