<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.service.assertion_validator' shared service.

return $this->services['lightsaml.service.assertion_validator'] = new \LightSaml\Validator\Model\Assertion\AssertionValidator(${($_ = isset($this->services['lightsaml.service.name_id_validator']) ? $this->services['lightsaml.service.name_id_validator'] : ($this->services['lightsaml.service.name_id_validator'] = new \LightSaml\Validator\Model\NameId\NameIdValidator())) && false ?: '_'}, ${($_ = isset($this->services['lightsaml.service.subject_validator']) ? $this->services['lightsaml.service.subject_validator'] : $this->load('getLightsaml_Service_SubjectValidatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['lightsaml.service.statement_validator']) ? $this->services['lightsaml.service.statement_validator'] : ($this->services['lightsaml.service.statement_validator'] = new \LightSaml\Validator\Model\Statement\StatementValidator())) && false ?: '_'});
