<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.provider.name_id' shared service.

return $this->services['lightsaml.provider.name_id'] = new \LightSaml\Provider\NameID\FixedNameIdProvider();
