<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.service.binding_factory' shared service.

return $this->services['lightsaml.service.binding_factory'] = new \LightSaml\Binding\BindingFactory(${($_ = isset($this->services['lightsaml.system.event_dispatcher']) ? $this->services['lightsaml.system.event_dispatcher'] : ($this->services['lightsaml.system.event_dispatcher'] = new \Symfony\Component\EventDispatcher\EventDispatcher())) && false ?: '_'});
