<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.service.signature_resolver' shared service.

return $this->services['lightsaml.service.signature_resolver'] = new \LightSaml\Resolver\Signature\OwnSignatureResolver(${($_ = isset($this->services['lightsaml.service.credential_resolver']) ? $this->services['lightsaml.service.credential_resolver'] : $this->load('getLightsaml_Service_CredentialResolverService.php')) && false ?: '_'});
