<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.party.trust_options_store' shared service.

$this->services['lightsaml.party.trust_options_store'] = $instance = new \LightSaml\Store\TrustOptions\CompositeTrustOptionsStore();

$instance->add(${($_ = isset($this->services['mautic.security.saml.trust_store']) ? $this->services['mautic.security.saml.trust_store'] : $this->load('getMautic_Security_Saml_TrustStoreService.php')) && false ?: '_'});

return $instance;
