<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.helper.template.mautibot' shared service.

return $this->services['mautic.helper.template.mautibot'] = new \Mautic\CoreBundle\Templating\Helper\MautibotHelper();
