<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.mobile.notification_details' shared service.

return $this->services['mautic.form.type.mobile.notification_details'] = new \Mautic\NotificationBundle\Form\Type\MobileNotificationDetailsType(${($_ = isset($this->services['mautic.helper.integration']) ? $this->services['mautic.helper.integration'] : $this->getMautic_Helper_IntegrationService()) && false ?: '_'});
