<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.twilio.callback' shared service.

return $this->services['mautic.sms.twilio.callback'] = new \Mautic\SmsBundle\Integration\Twilio\TwilioCallback(${($_ = isset($this->services['mautic.sms.helper.contact']) ? $this->services['mautic.sms.helper.contact'] : $this->load('getMautic_Sms_Helper_ContactService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.sms.twilio.configuration']) ? $this->services['mautic.sms.twilio.configuration'] : $this->load('getMautic_Sms_Twilio_ConfigurationService.php')) && false ?: '_'});
