<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.helper.template.date' shared service.

return $this->services['mautic.helper.template.date'] = new \Mautic\CoreBundle\Templating\Helper\DateHelper($this->getEnv('nullable:resolve:MAUTIC_DATE_FORMAT_FULL'), $this->getEnv('nullable:resolve:MAUTIC_DATE_FORMAT_SHORT'), $this->getEnv('nullable:resolve:MAUTIC_DATE_FORMAT_DATEONLY'), $this->getEnv('nullable:resolve:MAUTIC_DATE_FORMAT_TIMEONLY'), ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.core_parameters']) ? $this->services['mautic.helper.core_parameters'] : ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))) && false ?: '_'});
