<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.helper.template.exception' shared service.

return $this->services['mautic.helper.template.exception'] = new \Mautic\CoreBundle\Templating\Helper\ExceptionHelper(($this->targetDirs[3].'/app'));
