<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.report.configbundle.subscriber' shared service.

return $this->services['mautic.report.configbundle.subscriber'] = new \Mautic\ReportBundle\EventListener\ConfigSubscriber();
