<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.company_change_score' shared service.

return $this->services['mautic.form.type.company_change_score'] = new \Mautic\LeadBundle\Form\Type\CompanyChangeScoreActionType();
