<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.callback_handler_container' shared service.

$this->services['mautic.sms.callback_handler_container'] = $instance = new \Mautic\SmsBundle\Callback\HandlerContainer();

$instance->registerHandler(${($_ = isset($this->services['mautic.sms.twilio.callback']) ? $this->services['mautic.sms.twilio.callback'] : $this->load('getMautic_Sms_Twilio_CallbackService.php')) && false ?: '_'});

return $instance;
