<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.pagetoken.subscriber' shared service.

return $this->services['mautic.pagetoken.subscriber'] = new \Mautic\PageBundle\EventListener\TokenSubscriber();
