<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.core.validator.file_upload' shared service.

return $this->services['mautic.core.validator.file_upload'] = new \Mautic\CoreBundle\Validator\FileUploadValidator(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
