<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.webhook.campaign.subscriber' shared service.

return $this->services['mautic.webhook.campaign.subscriber'] = new \Mautic\WebhookBundle\EventListener\CampaignSubscriber(${($_ = isset($this->services['mautic.webhook.campaign.helper']) ? $this->services['mautic.webhook.campaign.helper'] : $this->load('getMautic_Webhook_Campaign_HelperService.php')) && false ?: '_'});
