<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.constraint.alias' shared service.

return $this->services['mautic.lead.constraint.alias'] = new \Mautic\LeadBundle\Form\Validator\Constraints\UniqueUserAliasValidator(${($_ = isset($this->services['mautic.lead.repository.lead_list']) ? $this->services['mautic.lead.repository.lead_list'] : $this->load('getMautic_Lead_Repository_LeadListService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.user']) ? $this->services['mautic.helper.user'] : $this->getMautic_Helper_UserService()) && false ?: '_'});
