<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.citrix.fixture.load_citrix_data' shared service.

return $this->services['mautic.citrix.fixture.load_citrix_data'] = new \MauticPlugin\MauticCitrixBundle\Tests\DataFixtures\ORM\LoadCitrixData(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
