<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.generated.columns.doctrine.listener' shared service.

return $this->services['mautic.generated.columns.doctrine.listener'] = new \Mautic\CoreBundle\EventListener\DoctrineGeneratedColumnsListener(${($_ = isset($this->services['mautic.generated.columns.provider']) ? $this->services['mautic.generated.columns.provider'] : $this->load('getMautic_Generated_Columns_ProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});
