<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.role_list' shared service.

return $this->services['mautic.form.type.role_list'] = new \Mautic\UserBundle\Form\Type\RoleListType(${($_ = isset($this->services['mautic.user.model.role']) ? $this->services['mautic.user.model.role'] : $this->load('getMautic_User_Model_RoleService.php')) && false ?: '_'});
