<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.report.helper.report' shared service.

return $this->services['mautic.report.helper.report'] = new \Mautic\ReportBundle\Helper\ReportHelper();
