<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.focus.form.type.focus' shared service.

return $this->services['mautic.focus.form.type.focus'] = new \MauticPlugin\MauticFocusBundle\Form\Type\FocusType(${($_ = isset($this->services['mautic.security']) ? $this->services['mautic.security'] : $this->getMautic_SecurityService()) && false ?: '_'});
