<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.email_dashboard_sent_email_to_contacts_widget' shared service.

return $this->services['mautic.form.type.email_dashboard_sent_email_to_contacts_widget'] = new \Mautic\EmailBundle\Form\Type\DashboardSentEmailToContactsWidgetType();
