<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.fullcontact_batch_lookup' shared service.

return $this->services['mautic.form.type.fullcontact_batch_lookup'] = new \MauticPlugin\MauticFullContactBundle\Form\Type\BatchLookupType();
