<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.company.campaign.action.type.form' shared service.

return $this->services['mautic.company.campaign.action.type.form'] = new \Mautic\LeadBundle\Form\Type\AddToCompanyActionType(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
