<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.subscriber' shared service.

$this->services['mautic.lead.subscriber'] = $instance = new \Mautic\LeadBundle\EventListener\LeadSubscriber(${($_ = isset($this->services['mautic.helper.ip_lookup']) ? $this->services['mautic.helper.ip_lookup'] : $this->getMautic_Helper_IpLookupService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.core.model.auditlog']) ? $this->services['mautic.core.model.auditlog'] : $this->getMautic_Core_Model_AuditlogService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.event.dispatcher']) ? $this->services['mautic.lead.event.dispatcher'] : $this->load('getMautic_Lead_Event_DispatcherService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.template.dnc_reason']) ? $this->services['mautic.helper.template.dnc_reason'] : $this->load('getMautic_Helper_Template_DncReasonService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});

$instance->setModelFactory(${($_ = isset($this->services['mautic.model.factory']) ? $this->services['mautic.model.factory'] : ($this->services['mautic.model.factory'] = new \Mautic\CoreBundle\Factory\ModelFactory($this))) && false ?: '_'});

return $instance;
