<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.transport.sendgrid_api.mail.metadata' shared service.

return $this->services['mautic.transport.sendgrid_api.mail.metadata'] = new \Mautic\EmailBundle\Swiftmailer\SendGrid\Mail\SendGridMailMetadata();
