<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.form.config.sync_settings' shared service.

return $this->services['mautic.integrations.form.config.sync_settings'] = new \Mautic\IntegrationsBundle\Form\Type\IntegrationSyncSettingsType();
