<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.social.formbundle.subscriber' shared service.

return $this->services['mautic.social.formbundle.subscriber'] = new \MauticPlugin\MauticSocialBundle\EventListener\FormSubscriber();
