<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.subscriber.determine_winner' shared service.

return $this->services['mautic.form.subscriber.determine_winner'] = new \Mautic\FormBundle\EventListener\DetermineWinnerSubscriber(${($_ = isset($this->services['mautic.form.repository.submission']) ? $this->services['mautic.form.repository.submission'] : $this->load('getMautic_Form_Repository_SubmissionService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
