<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.executioner.inactive' shared service.

return $this->services['mautic.campaign.executioner.inactive'] = new \Mautic\CampaignBundle\Executioner\InactiveExecutioner(${($_ = isset($this->services['mautic.campaign.contact_finder.inactive']) ? $this->services['mautic.campaign.contact_finder.inactive'] : $this->load('getMautic_Campaign_ContactFinder_InactiveService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.scheduler']) ? $this->services['mautic.campaign.scheduler'] : $this->load('getMautic_Campaign_SchedulerService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.helper.inactivity']) ? $this->services['mautic.campaign.helper.inactivity'] : $this->load('getMautic_Campaign_Helper_InactivityService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.event_executioner']) ? $this->services['mautic.campaign.event_executioner'] : $this->load('getMautic_Campaign_EventExecutionerService.php')) && false ?: '_'});
