<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.core.command.do_not_sell' shared service.

return $this->services['mautic.core.command.do_not_sell'] = new \Mautic\CoreBundle\Command\UpdateDoNotSellListCommand(${($_ = isset($this->services['mautic.helper.maxmind_do_not_sell_download']) ? $this->services['mautic.helper.maxmind_do_not_sell_download'] : $this->load('getMautic_Helper_MaxmindDoNotSellDownloadService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
