<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.helper.sync_judge' shared service.

return $this->services['mautic.integrations.helper.sync_judge'] = new \Mautic\IntegrationsBundle\Sync\SyncJudge\SyncJudge();
