<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.plugin.clearbit.lead.subscriber' shared service.

return $this->services['mautic.plugin.clearbit.lead.subscriber'] = new \MauticPlugin\MauticClearbitBundle\EventListener\LeadSubscriber(${($_ = isset($this->services['mautic.plugin.clearbit.lookup_helper']) ? $this->services['mautic.plugin.clearbit.lookup_helper'] : $this->load('getMautic_Plugin_Clearbit_LookupHelperService.php')) && false ?: '_'});
