<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.point.dashboard.subscriber' shared service.

return $this->services['mautic.point.dashboard.subscriber'] = new \Mautic\PointBundle\EventListener\DashboardSubscriber(${($_ = isset($this->services['mautic.point.model.point']) ? $this->services['mautic.point.model.point'] : $this->load('getMautic_Point_Model_PointService.php')) && false ?: '_'});
