<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.report.model.excel_exporter' shared service.

return $this->services['mautic.report.model.excel_exporter'] = new \Mautic\ReportBundle\Model\ExcelExporter(${($_ = isset($this->services['mautic.helper.template.formatter']) ? $this->services['mautic.helper.template.formatter'] : $this->load('getMautic_Helper_Template_FormatterService.php')) && false ?: '_'});
