<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.security.saml.user_creator' shared service.

return $this->services['mautic.security.saml.user_creator'] = new \Mautic\UserBundle\Security\SAML\User\UserCreator(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.security.saml.username_mapper']) ? $this->services['mautic.security.saml.username_mapper'] : $this->load('getMautic_Security_Saml_UsernameMapperService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.user.model.user']) ? $this->services['mautic.user.model.user'] : $this->getMautic_User_Model_UserService()) && false ?: '_'}, ${($_ = isset($this->services['security.encoder_factory']) ? $this->services['security.encoder_factory'] : $this->getSecurity_EncoderFactoryService()) && false ?: '_'}, $this->getEnv('nullable:resolve:MAUTIC_SAML_IDP_DEFAULT_ROLE'));
