<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.install.configurator.step.check' shared service.

$a = ${($_ = isset($this->services['mautic.configurator']) ? $this->services['mautic.configurator'] : $this->load('getMautic_ConfiguratorService.php')) && false ?: '_'};

if (isset($this->services['mautic.install.configurator.step.check'])) {
    return $this->services['mautic.install.configurator.step.check'];
}

return $this->services['mautic.install.configurator.step.check'] = new \Mautic\InstallBundle\Configurator\Step\CheckStep($a, ($this->targetDirs[3].'/app'), ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'}, ${($_ = isset($this->services['mautic.cipher.openssl']) ? $this->services['mautic.cipher.openssl'] : ($this->services['mautic.cipher.openssl'] = new \Mautic\CoreBundle\Security\Cryptography\Cipher\Symmetric\OpenSSLCipher('prod'))) && false ?: '_'});
