<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.point.type.genericstage_settings' shared service.

return $this->services['mautic.point.type.genericstage_settings'] = new \Mautic\StageBundle\Form\Type\GenericStageSettingsType();
