<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.fixture.campaign' shared service.

return $this->services['mautic.campaign.fixture.campaign'] = new \Mautic\CampaignBundle\DataFixtures\ORM\CampaignData();
