<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.page_abtest_settings' shared service.

return $this->services['mautic.form.type.page_abtest_settings'] = new \Mautic\PageBundle\Form\Type\AbTestPropertiesType();
