<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.point.leadbundle.subscriber' shared service.

return $this->services['mautic.point.leadbundle.subscriber'] = new \Mautic\PointBundle\EventListener\LeadSubscriber(${($_ = isset($this->services['mautic.point.model.trigger']) ? $this->services['mautic.point.model.trigger'] : $this->load('getMautic_Point_Model_TriggerService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.repository.points_change_log']) ? $this->services['mautic.lead.repository.points_change_log'] : $this->load('getMautic_Lead_Repository_PointsChangeLogService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.point.repository.lead_point_log']) ? $this->services['mautic.point.repository.lead_point_log'] : $this->load('getMautic_Point_Repository_LeadPointLogService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.point.repository.lead_trigger_log']) ? $this->services['mautic.point.repository.lead_trigger_log'] : $this->load('getMautic_Point_Repository_LeadTriggerLogService.php')) && false ?: '_'});
