<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.menu.extra' shared service.

return $this->services['mautic.menu.extra'] = ${($_ = isset($this->services['mautic.menu.builder']) ? $this->services['mautic.menu.builder'] : $this->load('getMautic_Menu_BuilderService.php')) && false ?: '_'}->extraMenu();
