<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaignconfigbundle.subscriber' shared service.

return $this->services['mautic.campaignconfigbundle.subscriber'] = new \Mautic\CampaignBundle\EventListener\ConfigSubscriber();
