<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.message_queue.subscriber' shared service.

return $this->services['mautic.sms.message_queue.subscriber'] = new \Mautic\SmsBundle\EventListener\MessageQueueSubscriber(${($_ = isset($this->services['mautic.sms.model.sms']) ? $this->services['mautic.sms.model.sms'] : $this->load('getMautic_Sms_Model_SmsService.php')) && false ?: '_'});
