<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.auth_provider.api_key' shared service.

return $this->services['mautic.integrations.auth_provider.api_key'] = new \Mautic\IntegrationsBundle\Auth\Provider\ApiKey\HttpFactory();
