<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.campaignbundle.subscriber' shared service.

return $this->services['mautic.form.campaignbundle.subscriber'] = new \Mautic\FormBundle\EventListener\CampaignSubscriber(${($_ = isset($this->services['mautic.form.model.form']) ? $this->services['mautic.form.model.form'] : $this->getMautic_Form_Model_FormService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.form.model.submission']) ? $this->services['mautic.form.model.submission'] : $this->load('getMautic_Form_Model_SubmissionService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.executioner.realtime']) ? $this->services['mautic.campaign.executioner.realtime'] : $this->load('getMautic_Campaign_Executioner_RealtimeService.php')) && false ?: '_'});
