<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.helper.file_properties' shared service.

return $this->services['mautic.helper.file_properties'] = new \Mautic\CoreBundle\Helper\FileProperties();
