<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.transport.sendgrid_api.response' shared service.

return $this->services['mautic.transport.sendgrid_api.response'] = new \Mautic\EmailBundle\Swiftmailer\SendGrid\SendGridApiResponse(${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});
