<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.point.search.subscriber' shared service.

return $this->services['mautic.point.search.subscriber'] = new \Mautic\PointBundle\EventListener\SearchSubscriber(${($_ = isset($this->services['mautic.point.model.point']) ? $this->services['mautic.point.model.point'] : $this->load('getMautic_Point_Model_PointService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.point.model.trigger']) ? $this->services['mautic.point.model.trigger'] : $this->load('getMautic_Point_Model_TriggerService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.security']) ? $this->services['mautic.security'] : $this->getMautic_SecurityService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.templating']) ? $this->services['mautic.helper.templating'] : ($this->services['mautic.helper.templating'] = new \Mautic\CoreBundle\Helper\TemplatingHelper(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'}))) && false ?: '_'});
