<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.channel.campaignbundle.subscriber' shared service.

return $this->services['mautic.channel.campaignbundle.subscriber'] = new \Mautic\ChannelBundle\EventListener\CampaignSubscriber(${($_ = isset($this->services['mautic.channel.model.message']) ? $this->services['mautic.channel.model.message'] : $this->load('getMautic_Channel_Model_MessageService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.dispatcher.action']) ? $this->services['mautic.campaign.dispatcher.action'] : $this->load('getMautic_Campaign_Dispatcher_ActionService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.event_collector']) ? $this->services['mautic.campaign.event_collector'] : $this->load('getMautic_Campaign_EventCollectorService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
