<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.citrix.integration.request' shared service.

return $this->services['mautic.citrix.integration.request'] = new \MauticPlugin\MauticCitrixBundle\EventListener\IntegrationRequestSubscriber();
