<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.report.scheduler.report_scheduler_subscriber' shared service.

return $this->services['mautic.report.scheduler.report_scheduler_subscriber'] = new \Mautic\ReportBundle\Scheduler\EventListener\ReportSchedulerSubscriber(${($_ = isset($this->services['mautic.report.model.scheduler_planner']) ? $this->services['mautic.report.model.scheduler_planner'] : $this->load('getMautic_Report_Model_SchedulerPlannerService.php')) && false ?: '_'});
