<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.broadcast.query' shared service.

return $this->services['mautic.sms.broadcast.query'] = new \Mautic\SmsBundle\Broadcast\BroadcastQuery(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.sms.model.sms']) ? $this->services['mautic.sms.model.sms'] : $this->load('getMautic_Sms_Model_SmsService.php')) && false ?: '_'});
