<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.cloudstorage.remoteassetbrowse.subscriber' shared service.

return $this->services['mautic.cloudstorage.remoteassetbrowse.subscriber'] = new \MauticPlugin\MauticCloudStorageBundle\EventListener\RemoteAssetBrowseSubscriber();
