<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.helper.phone_number' shared service.

return $this->services['mautic.helper.phone_number'] = new \Mautic\CoreBundle\Helper\PhoneNumberHelper();
