<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.social.form.type.network.twitter.mention' shared service.

return $this->services['mautic.social.form.type.network.twitter.mention'] = new \MauticPlugin\MauticSocialBundle\Form\Type\TwitterMentionType();
