<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.dynamic_content_filter_entry_filters' shared service.

$this->services['mautic.form.type.dynamic_content_filter_entry_filters'] = $instance = new \Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryFiltersType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});

$instance->setConnection(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'});

return $instance;
