<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.message_list' shared service.

return $this->services['mautic.form.type.message_list'] = new \Mautic\ChannelBundle\Form\Type\MessageListType();
