<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.email_dashboard_emails_in_time_widget' shared service.

return $this->services['mautic.form.type.email_dashboard_emails_in_time_widget'] = new \Mautic\EmailBundle\Form\Type\DashboardEmailsInTimeWidgetType();
