<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.http.client.psr-18' shared service.

return $this->services['mautic.http.client.psr-18'] = new \RicardoFiorani\GuzzlePsr18Adapter\Client();
