<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.fixture.contact_field' shared service.

return $this->services['mautic.lead.fixture.contact_field'] = new \Mautic\LeadBundle\DataFixtures\ORM\LoadLeadFieldData();
