<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.core.js.subscriber' shared service.

return $this->services['mautic.core.js.subscriber'] = new \Mautic\NotificationBundle\EventListener\BuildJsSubscriber(${($_ = isset($this->services['mautic.helper.notification']) ? $this->services['mautic.helper.notification'] : $this->load('getMautic_Helper_NotificationService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.integration']) ? $this->services['mautic.helper.integration'] : $this->getMautic_Helper_IntegrationService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
