<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.form.config.integration' shared service.

return $this->services['mautic.integrations.form.config.integration'] = new \Mautic\IntegrationsBundle\Form\Type\IntegrationConfigType(${($_ = isset($this->services['mautic.integrations.helper.config_integrations']) ? $this->services['mautic.integrations.helper.config_integrations'] : $this->load('getMautic_Integrations_Helper_ConfigIntegrationsService.php')) && false ?: '_'});
