<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.emailbundle.subscriber' shared service.

return $this->services['mautic.form.emailbundle.subscriber'] = new \Mautic\FormBundle\EventListener\EmailSubscriber();
