<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.sync.integration_process' shared service.

return $this->services['mautic.integrations.sync.integration_process'] = new \Mautic\IntegrationsBundle\Sync\SyncProcess\Direction\Integration\IntegrationSyncProcess(${($_ = isset($this->services['mautic.integrations.helper.sync_date']) ? $this->services['mautic.integrations.helper.sync_date'] : $this->load('getMautic_Integrations_Helper_SyncDateService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.integrations.helper.sync_mapping']) ? $this->services['mautic.integrations.helper.sync_mapping'] : $this->load('getMautic_Integrations_Helper_SyncMappingService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.integrations.sync.integration_process.object_change_generator']) ? $this->services['mautic.integrations.sync.integration_process.object_change_generator'] : $this->load('getMautic_Integrations_Sync_IntegrationProcess_ObjectChangeGeneratorService.php')) && false ?: '_'});
