<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaignrange.type.action' shared service.

return $this->services['mautic.campaignrange.type.action'] = new \Mautic\CampaignBundle\Form\Type\EventType();
