<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.executioner.kickoff' shared service.

return $this->services['mautic.campaign.executioner.kickoff'] = new \Mautic\CampaignBundle\Executioner\KickoffExecutioner(${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.contact_finder.kickoff']) ? $this->services['mautic.campaign.contact_finder.kickoff'] : $this->load('getMautic_Campaign_ContactFinder_KickoffService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.event_executioner']) ? $this->services['mautic.campaign.event_executioner'] : $this->load('getMautic_Campaign_EventExecutionerService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.scheduler']) ? $this->services['mautic.campaign.scheduler'] : $this->load('getMautic_Campaign_SchedulerService.php')) && false ?: '_'});
