<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.subscriber.contact_tracker' shared service.

return $this->services['mautic.sms.subscriber.contact_tracker'] = new \Mautic\SmsBundle\EventListener\TrackingSubscriber(${($_ = isset($this->services['mautic.sms.repository.stat']) ? $this->services['mautic.sms.repository.stat'] : $this->load('getMautic_Sms_Repository_StatService.php')) && false ?: '_'});
