<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.dispatcher.condition' shared service.

return $this->services['mautic.campaign.dispatcher.condition'] = new \Mautic\CampaignBundle\Executioner\Dispatcher\ConditionDispatcher(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
