<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.validator.length' shared service.

return $this->services['mautic.lead.validator.length'] = new \Mautic\LeadBundle\Validator\Constraints\LengthValidator();
