<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.citrix.campaignevent' shared service.

return $this->services['mautic.form.type.citrix.campaignevent'] = new \MauticPlugin\MauticCitrixBundle\Form\Type\CitrixCampaignEventType(${($_ = isset($this->services['mautic.citrix.model.citrix']) ? $this->services['mautic.citrix.model.citrix'] : $this->load('getMautic_Citrix_Model_CitrixService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
