<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.install.configurator.step.doctrine' shared service.

$a = ${($_ = isset($this->services['mautic.configurator']) ? $this->services['mautic.configurator'] : $this->load('getMautic_ConfiguratorService.php')) && false ?: '_'};

if (isset($this->services['mautic.install.configurator.step.doctrine'])) {
    return $this->services['mautic.install.configurator.step.doctrine'];
}

return $this->services['mautic.install.configurator.step.doctrine'] = new \Mautic\InstallBundle\Configurator\Step\DoctrineStep($a);
