<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.fixture.company' shared service.

return $this->services['mautic.lead.fixture.company'] = new \Mautic\LeadBundle\DataFixtures\ORM\LoadCompanyData(${($_ = isset($this->services['mautic.lead.model.company']) ? $this->services['mautic.lead.model.company'] : $this->getMautic_Lead_Model_CompanyService()) && false ?: '_'});
