<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.model.event_log' shared service.

$this->services['mautic.campaign.model.event_log'] = $instance = new \Mautic\CampaignBundle\Model\EventLogModel(${($_ = isset($this->services['mautic.campaign.model.event']) ? $this->services['mautic.campaign.model.event'] : $this->load('getMautic_Campaign_Model_EventService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.model.campaign']) ? $this->services['mautic.campaign.model.campaign'] : $this->load('getMautic_Campaign_Model_CampaignService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.ip_lookup']) ? $this->services['mautic.helper.ip_lookup'] : $this->getMautic_Helper_IpLookupService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.scheduler']) ? $this->services['mautic.campaign.scheduler'] : $this->load('getMautic_Campaign_SchedulerService.php')) && false ?: '_'});

$instance->setEntityManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
$instance->setSecurity(${($_ = isset($this->services['mautic.security']) ? $this->services['mautic.security'] : $this->getMautic_SecurityService()) && false ?: '_'});
$instance->setDispatcher(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
$instance->setTranslator(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
$instance->setUserHelper(${($_ = isset($this->services['mautic.helper.user']) ? $this->services['mautic.helper.user'] : $this->getMautic_Helper_UserService()) && false ?: '_'});
$instance->setCoreParametersHelper(${($_ = isset($this->services['mautic.helper.core_parameters']) ? $this->services['mautic.helper.core_parameters'] : ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))) && false ?: '_'});
$instance->setRouter(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
$instance->setLogger(${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});

return $instance;
