<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.transport.momentum.service.swift_message' shared service.

return $this->services['mautic.transport.momentum.service.swift_message'] = new \Mautic\EmailBundle\Swiftmailer\Momentum\Service\SwiftMessageService();
