<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.dwc_list' shared service.

return $this->services['mautic.form.type.dwc_list'] = new \Mautic\DynamicContentBundle\Form\Type\DynamicContentListType();
