<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.dynamicContent.lead.subscriber' shared service.

return $this->services['mautic.dynamicContent.lead.subscriber'] = new \Mautic\DynamicContentBundle\EventListener\LeadSubscriber(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.dynamicContent.repository.stat']) ? $this->services['mautic.dynamicContent.repository.stat'] : $this->load('getMautic_DynamicContent_Repository_StatService.php')) && false ?: '_'});
