<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.transport.momentum.sparkpost' shared service.

return $this->services['mautic.transport.momentum.sparkpost'] = ${($_ = isset($this->services['mautic.sparkpost.factory']) ? $this->services['mautic.sparkpost.factory'] : $this->load('getMautic_Sparkpost_FactoryService.php')) && false ?: '_'}->create($this->getEnv('nullable:resolve:MAUTIC_MAILER_HOST'), $this->getEnv('nullable:resolve:MAUTIC_MAILER_API_KEY'), $this->getEnv('nullable:resolve:MAUTIC_MAILER_PORT'));
