<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.stage.leadbundle.subscriber' shared service.

return $this->services['mautic.stage.leadbundle.subscriber'] = new \Mautic\StageBundle\EventListener\LeadSubscriber(${($_ = isset($this->services['mautic.lead.repository.stages_lead_log']) ? $this->services['mautic.lead.repository.stages_lead_log'] : $this->load('getMautic_Lead_Repository_StagesLeadLogService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.stage.repository.lead_stage_log']) ? $this->services['mautic.stage.repository.lead_stage_log'] : $this->load('getMautic_Stage_Repository_LeadStageLogService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
