<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.lead_import' shared service.

return $this->services['mautic.form.type.lead_import'] = new \Mautic\LeadBundle\Form\Type\LeadImportType();
