<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.subscriber' shared service.

return $this->services['mautic.form.subscriber'] = new \Mautic\FormBundle\EventListener\FormSubscriber(${($_ = isset($this->services['mautic.helper.ip_lookup']) ? $this->services['mautic.helper.ip_lookup'] : $this->getMautic_Helper_IpLookupService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.core.model.auditlog']) ? $this->services['mautic.core.model.auditlog'] : $this->getMautic_Core_Model_AuditlogService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.mailer']) ? $this->services['mautic.helper.mailer'] : $this->getMautic_Helper_MailerService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.core_parameters']) ? $this->services['mautic.helper.core_parameters'] : ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
