<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Mautic\ChannelBundle\Form\Type\MessageType' shared service.

$this->services['Mautic\\ChannelBundle\\Form\\Type\\MessageType'] = $instance = new \Mautic\ChannelBundle\Form\Type\MessageType(${($_ = isset($this->services['mautic.channel.model.message']) ? $this->services['mautic.channel.model.message'] : $this->load('getMautic_Channel_Model_MessageService.php')) && false ?: '_'});

$instance->setSecurity(${($_ = isset($this->services['mautic.security']) ? $this->services['mautic.security'] : $this->getMautic_SecurityService()) && false ?: '_'});

return $instance;
