<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.membership.builder' shared service.

return $this->services['mautic.campaign.membership.builder'] = new \Mautic\CampaignBundle\Membership\MembershipBuilder(${($_ = isset($this->services['mautic.campaign.membership.manager']) ? $this->services['mautic.campaign.membership.manager'] : $this->load('getMautic_Campaign_Membership_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.repository.lead']) ? $this->services['mautic.campaign.repository.lead'] : $this->load('getMautic_Campaign_Repository_LeadService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.repository.lead']) ? $this->services['mautic.lead.repository.lead'] : $this->getMautic_Lead_Repository_LeadService()) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
