<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.helper.dynamicContent' shared service.

return $this->services['mautic.helper.dynamicContent'] = new \Mautic\DynamicContentBundle\Helper\DynamicContentHelper(${($_ = isset($this->services['mautic.dynamicContent.model.dynamicContent']) ? $this->services['mautic.dynamicContent.model.dynamicContent'] : $this->load('getMautic_DynamicContent_Model_DynamicContentService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.executioner.realtime']) ? $this->services['mautic.campaign.executioner.realtime'] : $this->load('getMautic_Campaign_Executioner_RealtimeService.php')) && false ?: '_'}, ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
