<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.command.deduplicate' shared service.

return $this->services['mautic.lead.command.deduplicate'] = new \Mautic\LeadBundle\Command\DeduplicateCommand(${($_ = isset($this->services['mautic.lead.deduper']) ? $this->services['mautic.lead.deduper'] : $this->load('getMautic_Lead_DeduperService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
