<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.transport.momentum.facade' shared service.

return $this->services['mautic.transport.momentum.facade'] = new \Mautic\EmailBundle\Swiftmailer\Momentum\Facade\MomentumFacade(${($_ = isset($this->services['mautic.transport.momentum.adapter']) ? $this->services['mautic.transport.momentum.adapter'] : $this->load('getMautic_Transport_Momentum_AdapterService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.transport.momentum.service.swift_message']) ? $this->services['mautic.transport.momentum.service.swift_message'] : ($this->services['mautic.transport.momentum.service.swift_message'] = new \Mautic\EmailBundle\Swiftmailer\Momentum\Service\SwiftMessageService())) && false ?: '_'}, ${($_ = isset($this->services['mautic.transport.momentum.validator.swift_message']) ? $this->services['mautic.transport.momentum.validator.swift_message'] : $this->load('getMautic_Transport_Momentum_Validator_SwiftMessageService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.transport.momentum.callback']) ? $this->services['mautic.transport.momentum.callback'] : $this->load('getMautic_Transport_Momentum_CallbackService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});
