<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.membership.manager' shared service.

return $this->services['mautic.campaign.membership.manager'] = new \Mautic\CampaignBundle\Membership\MembershipManager(${($_ = isset($this->services['mautic.campaign.membership.adder']) ? $this->services['mautic.campaign.membership.adder'] : $this->load('getMautic_Campaign_Membership_AdderService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.membership.remover']) ? $this->services['mautic.campaign.membership.remover'] : $this->load('getMautic_Campaign_Membership_RemoverService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.membership.event_dispatcher']) ? $this->services['mautic.campaign.membership.event_dispatcher'] : $this->load('getMautic_Campaign_Membership_EventDispatcherService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.repository.lead']) ? $this->services['mautic.campaign.repository.lead'] : $this->load('getMautic_Campaign_Repository_LeadService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});
