<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.focus.form.type.focusshow_list' shared service.

return $this->services['mautic.focus.form.type.focusshow_list'] = new \MauticPlugin\MauticFocusBundle\Form\Type\FocusShowType(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
