<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic_integration.pipedrive.export.lead' shared service.

return $this->services['mautic_integration.pipedrive.export.lead'] = new \MauticPlugin\MauticCrmBundle\Integration\Pipedrive\Export\LeadExport(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['mautic_integration.pipedrive.export.company']) ? $this->services['mautic_integration.pipedrive.export.company'] : $this->load('getMauticIntegration_Pipedrive_Export_CompanyService.php')) && false ?: '_'});
