<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.query.builder.special.leadlist' shared service.

return $this->services['mautic.lead.query.builder.special.leadlist'] = new \Mautic\LeadBundle\Segment\Query\Filter\SegmentReferenceFilterQueryBuilder(${($_ = isset($this->services['mautic.lead.model.random_parameter_name']) ? $this->services['mautic.lead.model.random_parameter_name'] : ($this->services['mautic.lead.model.random_parameter_name'] = new \Mautic\LeadBundle\Segment\RandomParameterName())) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.repository.lead_segment_query_builder']) ? $this->services['mautic.lead.repository.lead_segment_query_builder'] : $this->getMautic_Lead_Repository_LeadSegmentQueryBuilderService()) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.model.lead_segment_filter_factory']) ? $this->services['mautic.lead.model.lead_segment_filter_factory'] : $this->getMautic_Lead_Model_LeadSegmentFilterFactoryService()) && false ?: '_'});
