<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.config.subscriber' shared service.

return $this->services['mautic.config.subscriber'] = new \Mautic\ConfigBundle\EventListener\ConfigSubscriber(${($_ = isset($this->services['mautic.helper.core_parameters']) ? $this->services['mautic.helper.core_parameters'] : ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))) && false ?: '_'}, $this, ${($_ = isset($this->services['mautic.config.config_change_logger']) ? $this->services['mautic.config.config_change_logger'] : $this->load('getMautic_Config_ConfigChangeLoggerService.php')) && false ?: '_'});
