<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.transport.sendgrid_api' shared service.

return $this->services['mautic.transport.sendgrid_api'] = new \Mautic\EmailBundle\Swiftmailer\Transport\SendgridApiTransport(${($_ = isset($this->services['mautic.transport.sendgrid_api.facade']) ? $this->services['mautic.transport.sendgrid_api.facade'] : $this->load('getMautic_Transport_SendgridApi_FacadeService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.transport.sendgrid_api.calback']) ? $this->services['mautic.transport.sendgrid_api.calback'] : $this->load('getMautic_Transport_SendgridApi_CalbackService.php')) && false ?: '_'});
