<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.command.validate' shared service.

return $this->services['mautic.campaign.command.validate'] = new \Mautic\CampaignBundle\Command\ValidateEventCommand(${($_ = isset($this->services['mautic.campaign.executioner.inactive']) ? $this->services['mautic.campaign.executioner.inactive'] : $this->load('getMautic_Campaign_Executioner_InactiveService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.template.formatter']) ? $this->services['mautic.helper.template.formatter'] : $this->load('getMautic_Helper_Template_FormatterService.php')) && false ?: '_'});
