<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.scheduler.datetime' shared service.

return $this->services['mautic.campaign.scheduler.datetime'] = new \Mautic\CampaignBundle\Executioner\Scheduler\Mode\DateTime(${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});
