<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.update.step.delete_cache' shared service.

return $this->services['mautic.update.step.delete_cache'] = new \Mautic\CoreBundle\Update\Step\DeleteCacheStep(${($_ = isset($this->services['mautic.helper.cache']) ? $this->services['mautic.helper.cache'] : $this->load('getMautic_Helper_CacheService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
