<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.transport.sparkpost' shared service.

return $this->services['mautic.transport.sparkpost'] = new \Mautic\EmailBundle\Swiftmailer\Transport\SparkpostTransport($this->getEnv('nullable:resolve:MAUTIC_MAILER_API_KEY'), ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.email.model.transport_callback']) ? $this->services['mautic.email.model.transport_callback'] : $this->load('getMautic_Email_Model_TransportCallbackService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.sparkpost.factory']) ? $this->services['mautic.sparkpost.factory'] : $this->load('getMautic_Sparkpost_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});
