<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.asset.configbundle.subscriber' shared service.

return $this->services['mautic.asset.configbundle.subscriber'] = new \Mautic\AssetBundle\EventListener\ConfigSubscriber();
