<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.sync.internal_process' shared service.

return $this->services['mautic.integrations.sync.internal_process'] = new \Mautic\IntegrationsBundle\Sync\SyncProcess\Direction\Internal\MauticSyncProcess(${($_ = isset($this->services['mautic.integrations.helper.sync_date']) ? $this->services['mautic.integrations.helper.sync_date'] : $this->load('getMautic_Integrations_Helper_SyncDateService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.integrations.sync.internal_process.object_change_generator']) ? $this->services['mautic.integrations.sync.internal_process.object_change_generator'] : $this->load('getMautic_Integrations_Sync_InternalProcess_ObjectChangeGeneratorService.php')) && false ?: '_'});
