<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.helper.template.formatter' shared service.

return $this->services['mautic.helper.template.formatter'] = new \Mautic\CoreBundle\Templating\Helper\FormatterHelper(${($_ = isset($this->services['mautic.helper.template.date']) ? $this->services['mautic.helper.template.date'] : $this->load('getMautic_Helper_Template_DateService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
