<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.email.leadbundle.subscriber' shared service.

return $this->services['mautic.email.leadbundle.subscriber'] = new \Mautic\EmailBundle\EventListener\LeadSubscriber(${($_ = isset($this->services['mautic.email.repository.emailReply']) ? $this->services['mautic.email.repository.emailReply'] : $this->load('getMautic_Email_Repository_EmailReplyService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.email.repository.stat']) ? $this->services['mautic.email.repository.stat'] : $this->load('getMautic_Email_Repository_StatService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
