<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.pointtrigger.type.action' shared service.

return $this->services['mautic.pointtrigger.type.action'] = new \Mautic\PointBundle\Form\Type\TriggerEventType();
