<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.helper.company_object' shared service.

return $this->services['mautic.integrations.helper.company_object'] = new \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\ObjectHelper\CompanyObjectHelper(${($_ = isset($this->services['mautic.lead.model.company']) ? $this->services['mautic.lead.model.company'] : $this->getMautic_Lead_Model_CompanyService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.repository.company']) ? $this->services['mautic.lead.repository.company'] : $this->load('getMautic_Lead_Repository_CompanyService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'});
