<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.channel.subscriber' shared service.

return $this->services['mautic.sms.channel.subscriber'] = new \Mautic\SmsBundle\EventListener\ChannelSubscriber(${($_ = isset($this->services['mautic.sms.transport_chain']) ? $this->services['mautic.sms.transport_chain'] : $this->load('getMautic_Sms_TransportChainService.php')) && false ?: '_'});
