<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.configbundle.subscriber' shared service.

return $this->services['mautic.sms.configbundle.subscriber'] = new \Mautic\SmsBundle\EventListener\ConfigSubscriber();
