<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.email.campaignbundle.condition_subscriber' shared service.

return $this->services['mautic.email.campaignbundle.condition_subscriber'] = new \Mautic\EmailBundle\EventListener\CampaignConditionSubscriber(${($_ = isset($this->services['mautic.validator.email']) ? $this->services['mautic.validator.email'] : $this->getMautic_Validator_EmailService()) && false ?: '_'});
