<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.subscriber.ui_contact_integrations_tab' shared service.

return $this->services['mautic.integrations.subscriber.ui_contact_integrations_tab'] = new \Mautic\IntegrationsBundle\EventListener\UIContactIntegrationsTabSubscriber(${($_ = isset($this->services['mautic.integrations.repository.object_mapping']) ? $this->services['mautic.integrations.repository.object_mapping'] : $this->load('getMautic_Integrations_Repository_ObjectMappingService.php')) && false ?: '_'});
