<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.report.settings' shared service.

return $this->services['mautic.form.type.report.settings'] = new \Mautic\ReportBundle\Form\Type\ReportSettingsType();
