<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.helper.plain_text_message' shared service.

return $this->services['mautic.helper.plain_text_message'] = new \Mautic\EmailBundle\Helper\PlainTextMessageHelper();
