<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.auth_provider.oauth2twolegged' shared service.

return $this->services['mautic.integrations.auth_provider.oauth2twolegged'] = new \Mautic\IntegrationsBundle\Auth\Provider\Oauth2TwoLegged\HttpFactory();
