<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.events.changeowner.type.form' shared service.

return $this->services['mautic.lead.events.changeowner.type.form'] = new \Mautic\LeadBundle\Form\Type\ChangeOwnerType(${($_ = isset($this->services['mautic.user.model.user']) ? $this->services['mautic.user.model.user'] : $this->getMautic_User_Model_UserService()) && false ?: '_'});
