<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.sync.notification.handler_contact' shared service.

return $this->services['mautic.integrations.sync.notification.handler_contact'] = new \Mautic\IntegrationsBundle\Sync\Notification\Handler\ContactNotificationHandler(${($_ = isset($this->services['mautic.integrations.sync.notification.writer']) ? $this->services['mautic.integrations.sync.notification.writer'] : $this->load('getMautic_Integrations_Sync_Notification_WriterService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.repository.lead_event_log']) ? $this->services['mautic.lead.repository.lead_event_log'] : $this->load('getMautic_Lead_Repository_LeadEventLogService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.integrations.sync.notification.helper_user_summary_notification']) ? $this->services['mautic.integrations.sync.notification.helper_user_summary_notification'] : $this->load('getMautic_Integrations_Sync_Notification_HelperUserSummaryNotificationService.php')) && false ?: '_'});
