<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.stage.type.action' shared service.

return $this->services['mautic.stage.type.action'] = new \Mautic\StageBundle\Form\Type\StageActionType();
