<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.company.merge.type.form' shared service.

return $this->services['mautic.company.merge.type.form'] = new \Mautic\LeadBundle\Form\Type\CompanyMergeType();
