<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.dynamicContent.subscriber.channel' shared service.

return $this->services['mautic.dynamicContent.subscriber.channel'] = new \Mautic\DynamicContentBundle\EventListener\ChannelSubscriber();
