<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.translation.loader' shared service.

return $this->services['mautic.translation.loader'] = new \Mautic\CoreBundle\Loader\TranslationLoader(${($_ = isset($this->services['mautic.helper.bundle']) ? $this->services['mautic.helper.bundle'] : $this->getMautic_Helper_BundleService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.paths']) ? $this->services['mautic.helper.paths'] : $this->getMautic_Helper_PathsService()) && false ?: '_'});
