<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.auth_provider.token_persistence_factory' shared service.

return $this->services['mautic.integrations.auth_provider.token_persistence_factory'] = new \Mautic\IntegrationsBundle\Auth\Support\Oauth2\Token\TokenPersistenceFactory(${($_ = isset($this->services['mautic.integrations.helper']) ? $this->services['mautic.integrations.helper'] : $this->getMautic_Integrations_HelperService()) && false ?: '_'});
