<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.sync.notification.handler_container' shared service.

$this->services['mautic.integrations.sync.notification.handler_container'] = $instance = new \Mautic\IntegrationsBundle\Sync\Notification\Handler\HandlerContainer();

$instance->registerHandler(${($_ = isset($this->services['mautic.integrations.sync.notification.handler_company']) ? $this->services['mautic.integrations.sync.notification.handler_company'] : $this->load('getMautic_Integrations_Sync_Notification_HandlerCompanyService.php')) && false ?: '_'});
$instance->registerHandler(${($_ = isset($this->services['mautic.integrations.sync.notification.handler_contact']) ? $this->services['mautic.integrations.sync.notification.handler_contact'] : $this->load('getMautic_Integrations_Sync_Notification_HandlerContactService.php')) && false ?: '_'});

return $instance;
