<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.queue.rabbitmq.subscriber' shared service.

return $this->services['mautic.queue.rabbitmq.subscriber'] = new \Mautic\QueueBundle\EventListener\RabbitMqSubscriber($this);
