<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.contact_finder.scheduled' shared service.

return $this->services['mautic.campaign.contact_finder.scheduled'] = new \Mautic\CampaignBundle\Executioner\ContactFinder\ScheduledContactFinder(${($_ = isset($this->services['mautic.lead.repository.lead']) ? $this->services['mautic.lead.repository.lead'] : $this->getMautic_Lead_Repository_LeadService()) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});
