<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.subscriber.donotcontact' shared service.

return $this->services['mautic.lead.subscriber.donotcontact'] = new \Mautic\LeadBundle\EventListener\DoNotContactSubscriber(${($_ = isset($this->services['mautic.lead.model.dnc']) ? $this->services['mautic.lead.model.dnc'] : $this->load('getMautic_Lead_Model_DncService.php')) && false ?: '_'});
