<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.page.campaignbundle.subscriber' shared service.

return $this->services['mautic.page.campaignbundle.subscriber'] = new \Mautic\PageBundle\EventListener\CampaignSubscriber(${($_ = isset($this->services['mautic.lead.model.lead']) ? $this->services['mautic.lead.model.lead'] : $this->getMautic_Lead_Model_LeadService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.page.helper.tracking']) ? $this->services['mautic.page.helper.tracking'] : $this->load('getMautic_Page_Helper_TrackingService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.executioner.realtime']) ? $this->services['mautic.campaign.executioner.realtime'] : $this->load('getMautic_Campaign_Executioner_RealtimeService.php')) && false ?: '_'});
