<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.command.sync' shared service.

return $this->services['mautic.integrations.command.sync'] = new \Mautic\IntegrationsBundle\Command\SyncCommand(${($_ = isset($this->services['mautic.integrations.sync.service']) ? $this->services['mautic.integrations.sync.service'] : $this->load('getMautic_Integrations_Sync_ServiceService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.core_parameters']) ? $this->services['mautic.helper.core_parameters'] : ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))) && false ?: '_'});
