<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.helper.inactivity' shared service.

return $this->services['mautic.campaign.helper.inactivity'] = new \Mautic\CampaignBundle\Executioner\Helper\InactiveHelper(${($_ = isset($this->services['mautic.campaign.scheduler']) ? $this->services['mautic.campaign.scheduler'] : $this->load('getMautic_Campaign_SchedulerService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.contact_finder.inactive']) ? $this->services['mautic.campaign.contact_finder.inactive'] : $this->load('getMautic_Campaign_ContactFinder_InactiveService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.repository.lead_event_log']) ? $this->services['mautic.campaign.repository.lead_event_log'] : $this->load('getMautic_Campaign_Repository_LeadEventLogService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.repository.event']) ? $this->services['mautic.campaign.repository.event'] : $this->load('getMautic_Campaign_Repository_EventService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});
