<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.lead_batch' shared service.

return $this->services['mautic.form.type.lead_batch'] = new \Mautic\LeadBundle\Form\Type\BatchType();
