<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.email.monitored.bounce.subscriber' shared service.

return $this->services['mautic.email.monitored.bounce.subscriber'] = new \Mautic\EmailBundle\EventListener\ProcessBounceSubscriber(${($_ = isset($this->services['mautic.message.processor.bounce']) ? $this->services['mautic.message.processor.bounce'] : $this->load('getMautic_Message_Processor_BounceService.php')) && false ?: '_'});
