<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.user' shared service.

return $this->services['mautic.form.type.user'] = new \Mautic\UserBundle\Form\Type\UserType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.user.model.user']) ? $this->services['mautic.user.model.user'] : $this->getMautic_User_Model_UserService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.language']) ? $this->services['mautic.helper.language'] : $this->load('getMautic_Helper_LanguageService.php')) && false ?: '_'});
