<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.focus.helper.token' shared service.

return $this->services['mautic.focus.helper.token'] = new \MauticPlugin\MauticFocusBundle\Helper\TokenHelper(${($_ = isset($this->services['mautic.focus.model.focus']) ? $this->services['mautic.focus.model.focus'] : $this->getMautic_Focus_Model_FocusService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.security']) ? $this->services['mautic.security'] : $this->getMautic_SecurityService()) && false ?: '_'});
