<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.webhook.notificator.webhookkillnotificator' shared service.

return $this->services['mautic.webhook.notificator.webhookkillnotificator'] = new \Mautic\WebhookBundle\Notificator\WebhookKillNotificator(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.core.model.notification']) ? $this->services['mautic.core.model.notification'] : $this->getMautic_Core_Model_NotificationService()) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.mailer']) ? $this->services['mautic.helper.mailer'] : $this->getMautic_Helper_MailerService()) && false ?: '_'});
