<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.page.leadbundle.subscriber' shared service.

$this->services['mautic.page.leadbundle.subscriber'] = $instance = new \Mautic\PageBundle\EventListener\LeadSubscriber(${($_ = isset($this->services['mautic.page.model.page']) ? $this->services['mautic.page.model.page'] : $this->getMautic_Page_Model_PageService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.page.model.video']) ? $this->services['mautic.page.model.video'] : $this->load('getMautic_Page_Model_VideoService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});

$instance->setModelFactory(${($_ = isset($this->services['mautic.model.factory']) ? $this->services['mautic.model.factory'] : ($this->services['mautic.model.factory'] = new \Mautic\CoreBundle\Factory\ModelFactory($this))) && false ?: '_'});

return $instance;
