<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.executioner.scheduled' shared service.

return $this->services['mautic.campaign.executioner.scheduled'] = new \Mautic\CampaignBundle\Executioner\ScheduledExecutioner(${($_ = isset($this->services['mautic.campaign.repository.lead_event_log']) ? $this->services['mautic.campaign.repository.lead_event_log'] : $this->load('getMautic_Campaign_Repository_LeadEventLogService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.event_executioner']) ? $this->services['mautic.campaign.event_executioner'] : $this->load('getMautic_Campaign_EventExecutionerService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.scheduler']) ? $this->services['mautic.campaign.scheduler'] : $this->load('getMautic_Campaign_SchedulerService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.contact_finder.scheduled']) ? $this->services['mautic.campaign.contact_finder.scheduled'] : $this->load('getMautic_Campaign_ContactFinder_ScheduledService.php')) && false ?: '_'});
