<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.campaignevent_lead_campaigns' shared service.

return $this->services['mautic.form.type.campaignevent_lead_campaigns'] = new \Mautic\LeadBundle\Form\Type\CampaignEventLeadCampaignsType(${($_ = isset($this->services['mautic.lead.model.list']) ? $this->services['mautic.lead.model.list'] : $this->getMautic_Lead_Model_ListService()) && false ?: '_'});
