<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.webhook.http.client' shared service.

return $this->services['mautic.webhook.http.client'] = new \Mautic\WebhookBundle\Http\Client(${($_ = isset($this->services['mautic.helper.core_parameters']) ? $this->services['mautic.helper.core_parameters'] : ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))) && false ?: '_'}, ${($_ = isset($this->services['mautic.guzzle.client']) ? $this->services['mautic.guzzle.client'] : $this->load('getMautic_Guzzle_ClientService.php')) && false ?: '_'});
