<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.social.tweet.list' shared service.

return $this->services['mautic.social.tweet.list'] = new \MauticPlugin\MauticSocialBundle\Form\Type\TweetListType();
