<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.campaignbundle.subscriber.send' shared service.

return $this->services['mautic.sms.campaignbundle.subscriber.send'] = new \Mautic\SmsBundle\EventListener\CampaignSendSubscriber(${($_ = isset($this->services['mautic.sms.model.sms']) ? $this->services['mautic.sms.model.sms'] : $this->load('getMautic_Sms_Model_SmsService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.sms.transport_chain']) ? $this->services['mautic.sms.transport_chain'] : $this->load('getMautic_Sms_TransportChainService.php')) && false ?: '_'});
