<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.entity_lookup' shared service.

return $this->services['mautic.form.type.entity_lookup'] = new \Mautic\CoreBundle\Form\Type\EntityLookupType(${($_ = isset($this->services['mautic.model.factory']) ? $this->services['mautic.model.factory'] : ($this->services['mautic.model.factory'] = new \Mautic\CoreBundle\Factory\ModelFactory($this))) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
