<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.focus.subscriber.page_bundle' shared service.

return $this->services['mautic.focus.subscriber.page_bundle'] = new \MauticPlugin\MauticFocusBundle\EventListener\PageSubscriber(${($_ = isset($this->services['mautic.security']) ? $this->services['mautic.security'] : $this->getMautic_SecurityService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.focus.model.focus']) ? $this->services['mautic.focus.model.focus'] : $this->getMautic_Focus_Model_FocusService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.token_builder.factory']) ? $this->services['mautic.helper.token_builder.factory'] : $this->load('getMautic_Helper_TokenBuilder_FactoryService.php')) && false ?: '_'});
