<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.helper.auth_integrations' shared service.

return $this->services['mautic.integrations.helper.auth_integrations'] = new \Mautic\IntegrationsBundle\Helper\AuthIntegrationsHelper(${($_ = isset($this->services['mautic.integrations.helper']) ? $this->services['mautic.integrations.helper'] : $this->getMautic_Integrations_HelperService()) && false ?: '_'});
