<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.type.trigger.leadchange' shared service.

return $this->services['mautic.campaign.type.trigger.leadchange'] = new \Mautic\CampaignBundle\Form\Type\CampaignEventLeadChangeType();
