<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.social.helper.campaign' shared service.

return $this->services['mautic.social.helper.campaign'] = new \MauticPlugin\MauticSocialBundle\Helper\CampaignEventHelper(${($_ = isset($this->services['mautic.helper.integration']) ? $this->services['mautic.helper.integration'] : $this->getMautic_Helper_IntegrationService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.page.model.trackable']) ? $this->services['mautic.page.model.trackable'] : $this->getMautic_Page_Model_TrackableService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.page.helper.token']) ? $this->services['mautic.page.helper.token'] : $this->getMautic_Page_Helper_TokenService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.asset.helper.token']) ? $this->services['mautic.asset.helper.token'] : $this->getMautic_Asset_Helper_TokenService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.social.model.tweet']) ? $this->services['mautic.social.model.tweet'] : $this->load('getMautic_Social_Model_TweetService.php')) && false ?: '_'});
