<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.update.step.finalize' shared service.

return $this->services['mautic.update.step.finalize'] = new \Mautic\CoreBundle\Update\Step\FinalizeUpdateStep(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.paths']) ? $this->services['mautic.helper.paths'] : $this->getMautic_Helper_PathsService()) && false ?: '_'}, ${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.app_version']) ? $this->services['mautic.helper.app_version'] : ($this->services['mautic.helper.app_version'] = new \Mautic\CoreBundle\Helper\AppVersion())) && false ?: '_'});
