<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.security.saml.credential_store' shared service.

return $this->services['mautic.security.saml.credential_store'] = new \Mautic\UserBundle\Security\SAML\Store\CredentialsStore(${($_ = isset($this->services['mautic.helper.core_parameters']) ? $this->services['mautic.helper.core_parameters'] : ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))) && false ?: '_'}, $this->getEnv('MAUTIC_SAML_ENTITY_ID'));
