<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.form.config.sync_settings_object_field_mapping' shared service.

return $this->services['mautic.integrations.form.config.sync_settings_object_field_mapping'] = new \Mautic\IntegrationsBundle\Form\Type\IntegrationSyncSettingsObjectFieldMappingType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.integrations.sync.data_exchange.mautic.field_helper']) ? $this->services['mautic.integrations.sync.data_exchange.mautic.field_helper'] : $this->load('getMautic_Integrations_Sync_DataExchange_Mautic_FieldHelperService.php')) && false ?: '_'});
