<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.button_group' shared service.

return $this->services['mautic.form.type.button_group'] = new \Mautic\CoreBundle\Form\Type\ButtonGroupType();
