<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.sms.campaign_reply_type' shared service.

return $this->services['mautic.form.type.sms.campaign_reply_type'] = new \Mautic\SmsBundle\Form\Type\CampaignReplyType();
