<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.lead_categories' shared service.

return $this->services['mautic.form.type.lead_categories'] = new \Mautic\LeadBundle\Form\Type\LeadCategoryType(${($_ = isset($this->services['mautic.category.model.category']) ? $this->services['mautic.category.model.category'] : $this->getMautic_Category_Model_CategoryService()) && false ?: '_'});
