<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.notification.pagebundle.subscriber' shared service.

return $this->services['mautic.notification.pagebundle.subscriber'] = new \Mautic\NotificationBundle\EventListener\PageSubscriber(${($_ = isset($this->services['templating.helper.assets']) ? $this->services['templating.helper.assets'] : $this->getTemplating_Helper_AssetsService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.integration']) ? $this->services['mautic.helper.integration'] : $this->getMautic_Helper_IntegrationService()) && false ?: '_'});
