<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.service.field.value.transformer' shared service.

return $this->services['mautic.form.service.field.value.transformer'] = new \Mautic\FormBundle\Event\Service\FieldValueTransformer(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
