<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.fixture.test.page_hit' shared service.

return $this->services['mautic.lead.fixture.test.page_hit'] = new \Mautic\LeadBundle\Tests\DataFixtures\ORM\LoadPageHitData();
