<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.report.model.scheduler_date_builder' shared service.

return $this->services['mautic.report.model.scheduler_date_builder'] = new \Mautic\ReportBundle\Scheduler\Date\DateBuilder(${($_ = isset($this->services['mautic.report.model.scheduler_builder']) ? $this->services['mautic.report.model.scheduler_builder'] : $this->load('getMautic_Report_Model_SchedulerBuilderService.php')) && false ?: '_'});
