<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.dispatcher.decision' shared service.

return $this->services['mautic.campaign.dispatcher.decision'] = new \Mautic\CampaignBundle\Executioner\Dispatcher\DecisionDispatcher(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.legacy_event_dispatcher']) ? $this->services['mautic.campaign.legacy_event_dispatcher'] : $this->load('getMautic_Campaign_LegacyEventDispatcherService.php')) && false ?: '_'});
