<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.helper.template.canvas' shared service.

return $this->services['mautic.helper.template.canvas'] = new \Mautic\CoreBundle\Templating\Helper\SidebarCanvasHelper(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
