<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.subscriber.reply' shared service.

return $this->services['mautic.sms.subscriber.reply'] = new \Mautic\SmsBundle\EventListener\ReplySubscriber(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.repository.lead_event_log']) ? $this->services['mautic.lead.repository.lead_event_log'] : $this->load('getMautic_Lead_Repository_LeadEventLogService.php')) && false ?: '_'});
