<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.email.campaignbundle.subscriber' shared service.

return $this->services['mautic.email.campaignbundle.subscriber'] = new \Mautic\EmailBundle\EventListener\CampaignSubscriber(${($_ = isset($this->services['mautic.email.model.email']) ? $this->services['mautic.email.model.email'] : $this->load('getMautic_Email_Model_EmailService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.executioner.realtime']) ? $this->services['mautic.campaign.executioner.realtime'] : $this->load('getMautic_Campaign_Executioner_RealtimeService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.email.model.send_email_to_user']) ? $this->services['mautic.email.model.send_email_to_user'] : $this->load('getMautic_Email_Model_SendEmailToUserService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
