<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.page.fixture.page_category' shared service.

return $this->services['mautic.page.fixture.page_category'] = new \Mautic\PageBundle\DataFixtures\ORM\LoadPageCategoryData(${($_ = isset($this->services['mautic.category.model.category']) ? $this->services['mautic.category.model.category'] : $this->getMautic_Category_Model_CategoryService()) && false ?: '_'});
