<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.transport.momentum.adapter' shared service.

return $this->services['mautic.transport.momentum.adapter'] = new \Mautic\EmailBundle\Swiftmailer\Momentum\Adapter\Adapter(${($_ = isset($this->services['mautic.transport.momentum.sparkpost']) ? $this->services['mautic.transport.momentum.sparkpost'] : $this->load('getMautic_Transport_Momentum_SparkpostService.php')) && false ?: '_'});
