<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.guzzle.client' shared service.

return $this->services['mautic.guzzle.client'] = ${($_ = isset($this->services['mautic.guzzle.client.factory']) ? $this->services['mautic.guzzle.client.factory'] : ($this->services['mautic.guzzle.client.factory'] = new \Mautic\EmailBundle\Swiftmailer\Guzzle\ClientFactory())) && false ?: '_'}->create();
