<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.asset.leadbundle.subscriber' shared service.

return $this->services['mautic.asset.leadbundle.subscriber'] = new \Mautic\AssetBundle\EventListener\LeadSubscriber(${($_ = isset($this->services['mautic.asset.model.asset']) ? $this->services['mautic.asset.model.asset'] : $this->getMautic_Asset_Model_AssetService()) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.asset.repository.download']) ? $this->services['mautic.asset.repository.download'] : $this->load('getMautic_Asset_Repository_DownloadService.php')) && false ?: '_'});
