<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.email.type.batch_send' shared service.

return $this->services['mautic.email.type.batch_send'] = new \Mautic\EmailBundle\Form\Type\BatchSendType();
