<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.dynamicContent.campaignbundle.subscriber' shared service.

return $this->services['mautic.dynamicContent.campaignbundle.subscriber'] = new \Mautic\DynamicContentBundle\EventListener\CampaignSubscriber(${($_ = isset($this->services['mautic.dynamicContent.model.dynamicContent']) ? $this->services['mautic.dynamicContent.model.dynamicContent'] : $this->load('getMautic_DynamicContent_Model_DynamicContentService.php')) && false ?: '_'}, ${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'}, ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
