<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.leadpoints_action' shared service.

return $this->services['mautic.form.type.leadpoints_action'] = new \Mautic\LeadBundle\Form\Type\PointActionType();
