<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.reportbundle.report_utm_tag_subscriber' shared service.

return $this->services['mautic.lead.reportbundle.report_utm_tag_subscriber'] = new \Mautic\LeadBundle\EventListener\ReportUtmTagSubscriber(${($_ = isset($this->services['mautic.lead.reportbundle.fields_builder']) ? $this->services['mautic.lead.reportbundle.fields_builder'] : $this->load('getMautic_Lead_Reportbundle_FieldsBuilderService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.model.company_report_data']) ? $this->services['mautic.lead.model.company_report_data'] : $this->load('getMautic_Lead_Model_CompanyReportDataService.php')) && false ?: '_'});
