<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.lead.submitaction.removedonotcontact' shared service.

return $this->services['mautic.form.type.lead.submitaction.removedonotcontact'] = new \Mautic\LeadBundle\Form\Type\ActionRemoveDoNotContact();
