<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.emailconfig' shared service.

return $this->services['mautic.form.type.emailconfig'] = new \Mautic\EmailBundle\Form\Type\ConfigType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.email.transport_type']) ? $this->services['mautic.email.transport_type'] : $this->load('getMautic_Email_TransportTypeService.php')) && false ?: '_'});
