<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.message.processor.feedbackloop' shared service.

return $this->services['mautic.message.processor.feedbackloop'] = new \Mautic\EmailBundle\MonitoredEmail\Processor\FeedbackLoop(${($_ = isset($this->services['mautic.message.search.contact']) ? $this->services['mautic.message.search.contact'] : $this->load('getMautic_Message_Search_ContactService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.model.dnc']) ? $this->services['mautic.lead.model.dnc'] : $this->load('getMautic_Lead_Model_DncService.php')) && false ?: '_'});
