<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.social.subscriber.channel' shared service.

return $this->services['mautic.social.subscriber.channel'] = new \MauticPlugin\MauticSocialBundle\EventListener\ChannelSubscriber(${($_ = isset($this->services['mautic.helper.integration']) ? $this->services['mautic.helper.integration'] : $this->getMautic_Helper_IntegrationService()) && false ?: '_'});
