<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.user.fixture.user' shared service.

return $this->services['mautic.user.fixture.user'] = new \Mautic\UserBundle\DataFixtures\ORM\LoadUserData(${($_ = isset($this->services['security.encoder_factory']) ? $this->services['security.encoder_factory'] : $this->getSecurity_EncoderFactoryService()) && false ?: '_'});
