<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.install.fixture.report_data' shared service.

return $this->services['mautic.install.fixture.report_data'] = new \Mautic\InstallBundle\InstallFixtures\ORM\LoadReportData();
