<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.citrix.campaignaction' shared service.

return $this->services['mautic.form.type.citrix.campaignaction'] = new \MauticPlugin\MauticCitrixBundle\Form\Type\CitrixCampaignActionType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
