<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sparkpost.factory' shared service.

return $this->services['mautic.sparkpost.factory'] = new \Mautic\EmailBundle\Swiftmailer\Sparkpost\SparkpostFactory(${($_ = isset($this->services['mautic.guzzle.client']) ? $this->services['mautic.guzzle.client'] : $this->load('getMautic_Guzzle_ClientService.php')) && false ?: '_'});
