<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.subscriber.contact_object' shared service.

return $this->services['mautic.integrations.subscriber.contact_object'] = new \Mautic\IntegrationsBundle\EventListener\ContactObjectSubscriber(${($_ = isset($this->services['mautic.integrations.helper.contact_object']) ? $this->services['mautic.integrations.helper.contact_object'] : $this->load('getMautic_Integrations_Helper_ContactObjectService.php')) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
