<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.install.configurator.step.user' shared service.

return $this->services['mautic.install.configurator.step.user'] = new \Mautic\InstallBundle\Configurator\Step\UserStep();
