<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.pagehit.campaign_trigger' shared service.

return $this->services['mautic.form.type.pagehit.campaign_trigger'] = new \Mautic\PageBundle\Form\Type\CampaignEventPageHitType();
