<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.campaignbundle.subscriber.reply' shared service.

return $this->services['mautic.sms.campaignbundle.subscriber.reply'] = new \Mautic\SmsBundle\EventListener\CampaignReplySubscriber(${($_ = isset($this->services['mautic.sms.transport_chain']) ? $this->services['mautic.sms.transport_chain'] : $this->load('getMautic_Sms_TransportChainService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.campaign.executioner.realtime']) ? $this->services['mautic.campaign.executioner.realtime'] : $this->load('getMautic_Campaign_Executioner_RealtimeService.php')) && false ?: '_'});
