<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.email.model.send_email_to_contacts' shared service.

return $this->services['mautic.email.model.send_email_to_contacts'] = new \Mautic\EmailBundle\Model\SendEmailToContact(${($_ = isset($this->services['mautic.helper.mailer']) ? $this->services['mautic.helper.mailer'] : $this->getMautic_Helper_MailerService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.email.helper.stat']) ? $this->services['mautic.email.helper.stat'] : $this->load('getMautic_Email_Helper_StatService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.model.dnc']) ? $this->services['mautic.lead.model.dnc'] : $this->load('getMautic_Lead_Model_DncService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
