<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.deduper' shared service.

return $this->services['mautic.lead.deduper'] = new \Mautic\LeadBundle\Deduplicate\ContactDeduper(${($_ = isset($this->services['mautic.lead.model.field']) ? $this->services['mautic.lead.model.field'] : $this->getMautic_Lead_Model_FieldService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.merger']) ? $this->services['mautic.lead.merger'] : $this->load('getMautic_Lead_MergerService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.repository.lead']) ? $this->services['mautic.lead.repository.lead'] : $this->getMautic_Lead_Repository_LeadService()) && false ?: '_'});
