<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.security.saml.id_store' shared service.

return $this->services['mautic.security.saml.id_store'] = new \Mautic\UserBundle\Security\SAML\Store\IdStore(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['lightsaml.system.time_provider']) ? $this->services['lightsaml.system.time_provider'] : ($this->services['lightsaml.system.time_provider'] = new \LightSaml\Provider\TimeProvider\SystemTimeProvider())) && false ?: '_'});
