<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.security.authentication_handler' shared service.

return $this->services['mautic.security.authentication_handler'] = new \Mautic\UserBundle\Security\Authentication\AuthenticationHandler(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
