<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.notification.campaignbundle.subscriber' shared service.

return $this->services['mautic.notification.campaignbundle.subscriber'] = new \Mautic\NotificationBundle\EventListener\CampaignSubscriber(${($_ = isset($this->services['mautic.helper.integration']) ? $this->services['mautic.helper.integration'] : $this->getMautic_Helper_IntegrationService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.notification.model.notification']) ? $this->services['mautic.notification.model.notification'] : $this->load('getMautic_Notification_Model_NotificationService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.notification.api']) ? $this->services['mautic.notification.api'] : $this->load('getMautic_Notification_ApiService.php')) && false ?: '_'}, ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.model.dnc']) ? $this->services['mautic.lead.model.dnc'] : $this->load('getMautic_Lead_Model_DncService.php')) && false ?: '_'});
