<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.command.execute' shared service.

return $this->services['mautic.campaign.command.execute'] = new \Mautic\CampaignBundle\Command\ExecuteEventCommand(${($_ = isset($this->services['mautic.campaign.executioner.scheduled']) ? $this->services['mautic.campaign.executioner.scheduled'] : $this->load('getMautic_Campaign_Executioner_ScheduledService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.template.formatter']) ? $this->services['mautic.helper.template.formatter'] : $this->load('getMautic_Helper_Template_FormatterService.php')) && false ?: '_'});
