<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.plugin.integration.subscriber' shared service.

return $this->services['mautic.plugin.integration.subscriber'] = new \Mautic\PluginBundle\EventListener\IntegrationSubscriber(${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});
