<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.formsubmit_sendemail_admin' shared service.

return $this->services['mautic.form.type.formsubmit_sendemail_admin'] = new \Mautic\EmailBundle\Form\Type\FormSubmitActionUserEmailType();
