<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.campaign.helper.removed_contact_tracker' shared service.

return $this->services['mautic.campaign.helper.removed_contact_tracker'] = new \Mautic\CampaignBundle\Helper\RemovedContactTracker();
