<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.dashboard.subscriber' shared service.

return $this->services['mautic.form.dashboard.subscriber'] = new \Mautic\FormBundle\EventListener\DashboardSubscriber(${($_ = isset($this->services['mautic.form.model.submission']) ? $this->services['mautic.form.model.submission'] : $this->load('getMautic_Form_Model_SubmissionService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.form.model.form']) ? $this->services['mautic.form.model.form'] : $this->getMautic_Form_Model_FormService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
