<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.plugin.campaignbundle.subscriber' shared service.

$this->services['mautic.plugin.campaignbundle.subscriber'] = $instance = new \Mautic\PluginBundle\EventListener\CampaignSubscriber();

$instance->setIntegrationHelper(${($_ = isset($this->services['mautic.helper.integration']) ? $this->services['mautic.helper.integration'] : $this->getMautic_Helper_IntegrationService()) && false ?: '_'});

return $instance;
