<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.sync.helper.relations' shared service.

return $this->services['mautic.integrations.sync.helper.relations'] = new \Mautic\IntegrationsBundle\Sync\Helper\RelationsHelper(${($_ = isset($this->services['mautic.integrations.helper.sync_mapping']) ? $this->services['mautic.integrations.helper.sync_mapping'] : $this->load('getMautic_Integrations_Helper_SyncMappingService.php')) && false ?: '_'});
