<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.page.tracking.pixel.send' shared service.

return $this->services['mautic.page.tracking.pixel.send'] = new \Mautic\PageBundle\Form\Type\TrackingPixelSendType(${($_ = isset($this->services['mautic.page.helper.tracking']) ? $this->services['mautic.page.helper.tracking'] : $this->load('getMautic_Page_Helper_TrackingService.php')) && false ?: '_'});
