<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.broadcast.subscriber' shared service.

return $this->services['mautic.sms.broadcast.subscriber'] = new \Mautic\SmsBundle\EventListener\BroadcastSubscriber(${($_ = isset($this->services['mautic.sms.broadcast.executioner']) ? $this->services['mautic.sms.broadcast.executioner'] : $this->load('getMautic_Sms_Broadcast_ExecutionerService.php')) && false ?: '_'});
