<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.auth_provider.oauth1atwolegged' shared service.

return $this->services['mautic.integrations.auth_provider.oauth1atwolegged'] = new \Mautic\IntegrationsBundle\Auth\Provider\Oauth1aTwoLegged\HttpFactory();
