<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.integration.campaign' shared service.

return $this->services['mautic.form.type.integration.campaign'] = new \Mautic\PluginBundle\Form\Type\IntegrationCampaignsType();
