<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.email.helper.request.storage' shared service.

return $this->services['mautic.email.helper.request.storage'] = new \Mautic\EmailBundle\Helper\RequestStorageHelper(${($_ = isset($this->services['mautic.helper.cache_storage']) ? $this->services['mautic.helper.cache_storage'] : $this->load('getMautic_Helper_CacheStorageService.php')) && false ?: '_'});
