<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.type.coreconfig_monitored_mailboxes' shared service.

return $this->services['mautic.form.type.coreconfig_monitored_mailboxes'] = new \Mautic\EmailBundle\Form\Type\ConfigMonitoredMailboxesType(${($_ = isset($this->services['mautic.helper.mailbox']) ? $this->services['mautic.helper.mailbox'] : $this->load('getMautic_Helper_MailboxService.php')) && false ?: '_'});
