<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.transport.mailjet' shared service.

$this->services['mautic.transport.mailjet'] = $instance = new \Mautic\EmailBundle\Swiftmailer\Transport\MailjetTransport(${($_ = isset($this->services['mautic.email.model.transport_callback']) ? $this->services['mautic.email.model.transport_callback'] : $this->load('getMautic_Email_Model_TransportCallbackService.php')) && false ?: '_'}, $this->getEnv('bool:resolve:MAUTIC_MAILER_MAILJET_SANDBOX'), $this->getEnv('nullable:resolve:MAUTIC_MAILER_MAILJET_SANDBOX_DEFAULT_MAIL'));

$instance->setUsername($this->getEnv('nullable:resolve:MAUTIC_MAILER_USER'));
$instance->setPassword($this->getEnv('nullable:resolve:MAUTIC_MAILER_PASSWORD'));

return $instance;
