<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.token.parser' shared service.

return $this->services['mautic.integrations.token.parser'] = new \Mautic\IntegrationsBundle\Helper\TokenParser();
