<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.twilio.transport' shared service.

return $this->services['mautic.sms.twilio.transport'] = new \Mautic\SmsBundle\Integration\Twilio\TwilioTransport(${($_ = isset($this->services['mautic.sms.twilio.configuration']) ? $this->services['mautic.sms.twilio.configuration'] : $this->load('getMautic_Sms_Twilio_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});
