<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.user.token.repository' shared service.

return $this->services['mautic.user.token.repository'] = ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}->getRepository('Mautic\\UserBundle\\Entity\\UserToken');
