<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.update.step.install_new_files' shared service.

return $this->services['mautic.update.step.install_new_files'] = new \Mautic\CoreBundle\Update\Step\InstallNewFilesStep(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.update']) ? $this->services['mautic.helper.update'] : $this->getMautic_Helper_UpdateService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.paths']) ? $this->services['mautic.helper.paths'] : $this->getMautic_Helper_PathsService()) && false ?: '_'});
