<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.form.fixture.form_result' shared service.

return $this->services['mautic.form.fixture.form_result'] = new \Mautic\FormBundle\DataFixtures\ORM\LoadFormResultData(${($_ = isset($this->services['mautic.page.model.page']) ? $this->services['mautic.page.model.page'] : $this->getMautic_Page_Model_PageService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.form.model.submission']) ? $this->services['mautic.form.model.submission'] : $this->load('getMautic_Form_Model_SubmissionService.php')) && false ?: '_'});
