<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.sms.smsbundle.subscriber' shared service.

return $this->services['mautic.sms.smsbundle.subscriber'] = new \Mautic\SmsBundle\EventListener\SmsSubscriber(${($_ = isset($this->services['mautic.core.model.auditlog']) ? $this->services['mautic.core.model.auditlog'] : $this->getMautic_Core_Model_AuditlogService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.page.model.trackable']) ? $this->services['mautic.page.model.trackable'] : $this->getMautic_Page_Model_TrackableService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.page.helper.token']) ? $this->services['mautic.page.helper.token'] : $this->getMautic_Page_Helper_TokenService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.asset.helper.token']) ? $this->services['mautic.asset.helper.token'] : $this->getMautic_Asset_Helper_TokenService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.sms']) ? $this->services['mautic.helper.sms'] : $this->load('getMautic_Helper_SmsService.php')) && false ?: '_'});
