<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.report.command.export_scheduler' shared service.

return $this->services['mautic.report.command.export_scheduler'] = new \Mautic\ReportBundle\Scheduler\Command\ExportSchedulerCommand(${($_ = isset($this->services['mautic.report.model.report_exporter']) ? $this->services['mautic.report.model.report_exporter'] : $this->load('getMautic_Report_Model_ReportExporterService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
