<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_uploader.namer.urlsafe' shared service.

return $this->services['oneup_uploader.namer.urlsafe'] = new \Oneup\UploaderBundle\Uploader\Naming\UrlSafeNamer();
