<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_uploader.command.clear_orphans' shared service.

$this->services['oneup_uploader.command.clear_orphans'] = $instance = new \Oneup\UploaderBundle\Command\ClearOrphansCommand(${($_ = isset($this->services['oneup_uploader.orphanage_manager']) ? $this->services['oneup_uploader.orphanage_manager'] : $this->load('getOneupUploader_OrphanageManagerService.php')) && false ?: '_'});

$instance->setName('oneup:uploader:clear-orphans');

return $instance;
