<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_uploader.storage.asset' shared service.

return $this->services['oneup_uploader.storage.asset'] = new \Oneup\UploaderBundle\Uploader\Storage\FilesystemStorage($this->getEnv('nullable:resolve:MAUTIC_UPLOAD_DIR'));
