<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.session_strategy.dev' shared service.

return $this->services['security.authentication.session_strategy.dev'] = new \Symfony\Component\Security\Http\Session\SessionAuthenticationStrategy('migrate');
