<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.bazinga_oauth.api' shared service.

$this->services['security.authentication.provider.bazinga_oauth.api'] = $instance = new \Mautic\ApiBundle\Security\OAuth1\Authentication\Provider\OAuthProvider(${($_ = isset($this->services['mautic.user.provider']) ? $this->services['mautic.user.provider'] : $this->getMautic_User_ProviderService()) && false ?: '_'}, ${($_ = isset($this->services['bazinga.oauth.server_service']) ? $this->services['bazinga.oauth.server_service'] : $this->load('getBazinga_Oauth_ServerServiceService.php')) && false ?: '_'}, '');

$instance->setTranslator(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});

return $instance;
