<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.request_matcher.u_dnbxo' shared service.

return $this->services['security.request_matcher.u_dnbxo'] = new \Symfony\Component\HttpFoundation\RequestMatcher('^/s/login$');
