<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.request_matcher.22xzgpr' shared service.

return $this->services['security.request_matcher.22xzgpr'] = new \Symfony\Component\HttpFoundation\RequestMatcher('^/oauth/v1/request_token');
