<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'swiftmailer.mailer.default' shared service.

return $this->services['swiftmailer.mailer.default'] = new \Swift_Mailer(${($_ = isset($this->services['mautic.transport.spool']) ? $this->services['mautic.transport.spool'] : $this->getMautic_Transport_SpoolService()) && false ?: '_'});
