<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.rememberme.services.simplehash.main' shared service.

return $this->services['security.authentication.rememberme.services.simplehash.main'] = new \Symfony\Component\Security\Http\RememberMe\TokenBasedRememberMeServices([0 => ${($_ = isset($this->services['mautic.user.provider']) ? $this->services['mautic.user.provider'] : $this->getMautic_User_ProviderService()) && false ?: '_'}], $this->getEnv('nullable:resolve:MAUTIC_REMEMBERME_KEY'), 'main', ['lifetime' => 0, 'path' => $this->getEnv('nullable:resolve:MAUTIC_REMEMBERME_PATH'), 'domain' => $this->getEnv('nullable:resolve:MAUTIC_REMEMBERME_DOMAIN'), 'name' => 'REMEMBERME', 'secure' => false, 'httponly' => true, 'samesite' => NULL, 'always_remember_me' => false, 'remember_me_parameter' => '_remember_me'], ${($_ = isset($this->services['monolog.logger.security']) ? $this->services['monolog.logger.security'] : $this->load('getMonolog_Logger_SecurityService.php')) && false ?: '_'});
