<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'transifex.factory' shared service.

return $this->services['transifex.factory'] = new \Mautic\CoreBundle\Factory\TransifexFactory(${($_ = isset($this->services['mautic.http.client.psr-18']) ? $this->services['mautic.http.client.psr-18'] : ($this->services['mautic.http.client.psr-18'] = new \RicardoFiorani\GuzzlePsr18Adapter\Client())) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.core_parameters']) ? $this->services['mautic.helper.core_parameters'] : ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))) && false ?: '_'});
