<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.helper.form' shared service.

return $this->services['templating.helper.form'] = new \Mautic\CoreBundle\Templating\Helper\FormHelper(new \Symfony\Component\Form\FormRenderer(new \Symfony\Component\Form\Extension\Templating\TemplatingRendererEngine(${($_ = isset($this->services['templating.engine.php']) ? $this->services['templating.engine.php'] : $this->load('getTemplating_Engine_PhpService.php')) && false ?: '_'}, $this->parameters['templating.helper.form.resources']), ${($_ = isset($this->services['security.csrf.token_manager']) ? $this->services['security.csrf.token_manager'] : $this->getSecurity_Csrf_TokenManagerService()) && false ?: '_'}));
