<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.twig.extension.slot' shared service.

return $this->services['templating.twig.extension.slot'] = new \Mautic\CoreBundle\Templating\Twig\Extension\SlotExtension(${($_ = isset($this->services['templating.helper.slots']) ? $this->services['templating.helper.slots'] : ($this->services['templating.helper.slots'] = new \Mautic\CoreBundle\Templating\Helper\SlotsHelper())) && false ?: '_'});
