<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Mautic\InstallBundle\Configurator\Form\UserStepType' shared service.

return $this->services['Mautic\\InstallBundle\\Configurator\\Form\\UserStepType'] = new \Mautic\InstallBundle\Configurator\Form\UserStepType(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'});
