name: Drupal Deploy Dev

on:
  push:
    branches: [ "test" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP without any shared extensions except mbstring
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete --exclude 'web/sites/default/files' --exclude 'web/sites/default/settings.local.php' --exclude 'web/mkt'
        path: ./
        remote_path: '/home2/renata/dev.orsefotografia.com.br/'
        remote_host: 64.20.40.138
        remote_port: 1140
        remote_user: 'renata'
        remote_key: ${{ secrets.DEPLOY_KEY }}
        remote_key_pass: ${{ secrets.DEPLOY_KEY_PASS }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 64.20.40.138
        username: renata
        key: ${{ secrets.DEPLOY_KEY }}
        passphrase: ${{ secrets.DEPLOY_KEY_PASS }}
        port: 1140
        script: |
          cd /home2/renata/dev.orsefotografia.com.br/
          ./vendor/bin/drush deploy
