name: Drupal Deploy Dev

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP without any shared extensions except mbstring
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr
        path: ./
        remote_path: '/home/u711810234/domains/orsefotografia.com.br/public_html/dev/'
        remote_host: 82.180.159.192
        remote_port: 65002
        remote_user: 'u711810234'
        remote_key: ${{ secrets.DEPLOY_KEY }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 82.180.159.192
        username: u711810234
        key: ${{ secrets.DEPLOY_KEY }}
        port: 65002
        script: |
          cd /home/u711810234/domains/orsefotografia.com.br/public_html/dev/
          ./vendor/bin/drush deploy
